<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="et" xml:lang="et"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Regressioonimudeli kasutamine – Põhjuslike seoste hindamine majanduses</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-difdif.html" rel="next">
<link href="./02-pomate.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Tulemusi pole",
    "search-matching-documents-text": "sobivat dokumenti",
    "search-copy-link-title": "Kopeeri link otsingule",
    "search-hide-matches-text": "Peida lisavastavused",
    "search-more-match-text": "veel üks vastavus selles dokumendis",
    "search-more-matches-text": "rohkem vastavusi selles dokumendis",
    "search-clear-button-title": "Puhasta",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Tühista",
    "search-submit-button-title": "Esita",
    "search-label": "Otsi"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Lülita külgriba navigeerimist" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-regressioon.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regressioonimudeli kasutamine</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Lülita külgriba navigeerimist" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Otsi" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Põhjuslike seoste hindamine majanduses</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Otsi"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sissejuhatus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-dag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Suunatud atsüklilised graafid (DAG)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-pomate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Potentsiaalse tulemuse mudel</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-regressioon.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regressioonimudeli kasutamine</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-difdif.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Juurdekasvude erinevus (DIF-DIF)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-rdd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regressiooni katkemise meetod</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-sobitamine.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Sobitamine</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-ivmeetod.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Instrumentmuutuja</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-synthcontr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sünteetilise võrdlusobjekti meetod</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-mlpuumets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Masinõppemudelid</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-mllasso.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">LASSO mõju hindamisel</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-tehajaideed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Teha</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pohimoistedkordamiseks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Põhimõisted eksamiks kordamiseks</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sisukord</h2>
   
  <ul>
  <li><a href="#sissejuhatus" id="toc-sissejuhatus" class="nav-link active" data-scroll-target="#sissejuhatus"><span class="header-section-number">3.1</span> Sissejuhatus</a></li>
  <li><a href="#tavaline-regressioonimudel" id="toc-tavaline-regressioonimudel" class="nav-link" data-scroll-target="#tavaline-regressioonimudel"><span class="header-section-number">3.2</span> Tavaline regressioonimudel</a></li>
  <li><a href="#regressioonimudel-interaktsiooniga-heterogeenne-mõju" id="toc-regressioonimudel-interaktsiooniga-heterogeenne-mõju" class="nav-link" data-scroll-target="#regressioonimudel-interaktsiooniga-heterogeenne-mõju"><span class="header-section-number">3.3</span> Regressioonimudel interaktsiooniga (heterogeenne mõju)</a></li>
  <li><a href="#kaks-eraldi-regressioonimudelit" id="toc-kaks-eraldi-regressioonimudelit" class="nav-link" data-scroll-target="#kaks-eraldi-regressioonimudelit"><span class="header-section-number">3.4</span> Kaks eraldi regressioonimudelit</a>
  <ul class="collapse">
  <li><a href="#g-arvutus-g-computation" id="toc-g-arvutus-g-computation" class="nav-link" data-scroll-target="#g-arvutus-g-computation">G-arvutus (<em>G-computation</em>)</a></li>
  </ul></li>
  <li><a href="#empiiriline-näide" id="toc-empiiriline-näide" class="nav-link" data-scroll-target="#empiiriline-näide"><span class="header-section-number">3.5</span> Empiiriline näide</a>
  <ul class="collapse">
  <li><a href="#muutujate-selgitused" id="toc-muutujate-selgitused" class="nav-link" data-scroll-target="#muutujate-selgitused">Muutujate selgitused</a></li>
  <li><a href="#vajalikud-paketid" id="toc-vajalikud-paketid" class="nav-link" data-scroll-target="#vajalikud-paketid">Vajalikud paketid</a></li>
  <li><a href="#andmestiku-lugemine" id="toc-andmestiku-lugemine" class="nav-link" data-scroll-target="#andmestiku-lugemine">Andmestiku lugemine</a></li>
  <li><a href="#kirjeldav-analüüs" id="toc-kirjeldav-analüüs" class="nav-link" data-scroll-target="#kirjeldav-analüüs">Kirjeldav analüüs</a></li>
  <li><a href="#regressioonimudel" id="toc-regressioonimudel" class="nav-link" data-scroll-target="#regressioonimudel">Regressioonimudel</a></li>
  <li><a href="#eraldi-mudelid-osalejatele-ja-mitteosalejatele" id="toc-eraldi-mudelid-osalejatele-ja-mitteosalejatele" class="nav-link" data-scroll-target="#eraldi-mudelid-osalejatele-ja-mitteosalejatele">Eraldi mudelid osalejatele ja mitteosalejatele</a></li>
  <li><a href="#usalduspiiride-leidmine" id="toc-usalduspiiride-leidmine" class="nav-link" data-scroll-target="#usalduspiiride-leidmine">Usalduspiiride leidmine</a></li>
  <li><a href="#bootstrapping-hinnangute-standardvea-leidmiseks---fännidele" id="toc-bootstrapping-hinnangute-standardvea-leidmiseks---fännidele" class="nav-link" data-scroll-target="#bootstrapping-hinnangute-standardvea-leidmiseks---fännidele">Bootstrapping hinnangute standardvea leidmiseks - fännidele</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Regressioonimudeli kasutamine</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    <div>
    <div class="quarto-title-meta-heading">Muudetud</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">23/09/2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="sissejuhatus" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sissejuhatus"><span class="header-section-number">3.1</span> Sissejuhatus</h2>
<p>Selles peatükis vaatame, kuidas hinnata põhjuslikku mõju regressioonimudeli abiga. Endiselt on meil eesmärk leida meetme <span class="math inline">\(D\)</span>, näiteks tööturukoolituse või turunduskampaania mõju väljundile <span class="math inline">\(Y\)</span>, näiteks palgale või ettevõtte müügitulemustele.</p>
<p>Meeldetuletuseks, põhjusliku mõju leidmiseks regressioonimudeliga peab endiselt kehtima tingliku sõltumatuse eeldus (CIA - <em>conditional independence assumption</em>).</p>
<p><span class="math display">\[E[Y^0 | D=1, \mathbf{X}] = E[Y^0 | D=0, \mathbf{X}]\]</span> ja <span class="math display">\[E[Y^1 | D=1, \mathbf{X}] = E[Y^1 | D=0, \mathbf{X}]\]</span></p>
<p>See tähendab, et pärast kõigi oluliste segavate tegurite <span class="math inline">\(\mathbf{X}\)</span> (<span class="math inline">\(X \rightarrow D\)</span> ja <span class="math inline">\(X \rightarrow Y\)</span>) arvesse võtmist ei ole potentsiaalsetel tulemustel <span class="math inline">\(Y^0\)</span> ja <span class="math inline">\(Y^1\)</span> ning meetmes osalemisel <span class="math inline">\(D\)</span> enam seost. Seega on meil osalejad ja mitteosalejad tehtud sarnaseks ja omavahel võrreldavaks.</p>
</section>
<section id="tavaline-regressioonimudel" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="tavaline-regressioonimudel"><span class="header-section-number">3.2</span> Tavaline regressioonimudel</h2>
<p>Kõige lihtsam mudel eeldab, et meetme mõju <span class="math inline">\(\delta\)</span> on homogeenne, st sama kõigi <span class="math inline">\(\mathbf{X}\)</span> väärtuste korral ja aditiivne.</p>
<p><span class="math display">\[Y_i = \alpha + \delta D_i + \beta_1 X_{1i} + \beta_2 X_{2i} + \dots + \epsilon_i\]</span></p>
<p><span class="math inline">\(\hat{\delta}\)</span> on hinnang keskmisele mõjule (ATE - <em>Average Treatment Effect</em>). Antud mudel tegelikult eeldab, et ATE = ATT = ATU ehk mõju on kõigile ühesugune.</p>
<p>Regressioonimudeli parameetrid hindame vähimruutude meetodi abil ja kasutame standardvigu, mis lubaksid ka heteroskedastiivsust (nn robustsed standardvead).</p>
<p>Sellise meetodi tugevuseks on tema lihtsus ning võimalus hinnata ka seose parameetrid siis, kui ühist tuge ei ole. Näiteks isegi kui meetmes osalejad on kõik vanusevahemikus 30-39, aga võrdlusgrupis on inimesed vanyuses 20-29 ja 40-60, siis eeldades vanuse lineaarset mõju saame ikkagi võtta vanuse efekti arvesse. (Sellisel juhul peab muidugi olema tõlgendamisel ettevaatlik.)</p>
<p>Sageli paneme regressioonimudelisse sisse ka sõltuva tunnuse väärtuse enne meedet, et võtta arvesse tunnuste inertsi, näiteks inimese varasem palk või ettevõtte varasem läbimüük.</p>
<p><span class="math display">\[Y_{iPost} = \alpha + \delta D_i + \beta_1 X_{1i} + \beta_2 X_{2i} + \gamma Y_{iPre} \dots + \epsilon_i\]</span> kus <span class="math inline">\(Y_{iPost}\)</span> on tulemus peale meedet ja <span class="math inline">\(Y_{iPre}\)</span> tulemus enne meedet.</p>
<p>See lähenemine on üsna sarnane erinevuste vahe meetodiga (<em>difference-in-differences</em>), millest tuleb eraldi juttu hiljem. Pangem aga tähele, et kui panna mudelisse viitajaga sõltuv muutuja, siis peab selle väärtus olema piisavalt enne meedet, et seda ei mõjutaks inimeste ootused meetme tuleku kohta, nii-nimetatud „<em>pre-treatment dip</em>“ (<em>lisada viide Ashenfelter (1978) artiklile</em>). Näiteks, kui töötav inimene teab, et teda varsti koondatakse ja ta peab minema kahe kuu pärast täiendõppekoolitusele, et õppida uus amet, siis juba praegusel kuul ta võib pingutada vähem ja saada vähem palka.</p>
</section>
<section id="regressioonimudel-interaktsiooniga-heterogeenne-mõju" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="regressioonimudel-interaktsiooniga-heterogeenne-mõju"><span class="header-section-number">3.3</span> Regressioonimudel interaktsiooniga (heterogeenne mõju)</h2>
<p>Kui on alust arvata, et meetme mõju <span class="math inline">\(D\)</span> sõltub mõnest tunnusest <span class="math inline">\(X_k\)</span> (st mõju on heterogeenne), siis saab seda arvesse võtta lisades mudelisse interaktsiooniliikme.</p>
<p><span class="math display">\[Y_i = \alpha + \delta D_i + \gamma (D_i \cdot X_{ki}) + \mathbf{X}_i \beta + \epsilon_i\]</span></p>
<p>Mõju sõltub nüüd inimese tunnustest. Väärtuse <span class="math inline">\(X_{ki}\)</span> korral on seega mõju hinnang <span class="math inline">\(\hat{\delta} + \hat{\gamma} X_{ki}\)</span>.</p>
<p>Ülal on kasutatud kompaktsemaks kirjutamiseks tähistusi, kus paksus kirjas <span class="math inline">\(\mathbf{X}_i\)</span> on selgitavate tunnuste reavektor <span class="math inline">\(i\)</span>-nda inimese jaoks <span class="math inline">\((X_{1i}, X_{2i}, ...)\)</span>, ja <span class="math inline">\(\beta\)</span> on parameetrite veeruvektor <span class="math inline">\((\beta_1, \beta_2, ...)'\)</span></p>
<p>Näiteks võib kliendikaardi mõju müügile olla erinev meestele ja naistele. Sellisel juhul peame lisama interaktsiooniliikme soo tunnuse ja kliendikaardi olemasolu kohta.</p>
<p>Seda mudelit kasutades hindame CATE (<em>Conditional Average Treatment Effect</em>), st keskmise mõju konkreetsete selgitavate väärtuste korral, näiteks meeste jaoks ja naiste jaoks. Kui soovime leida keskmise mõjuhinnangu (ATE), siis peame leidma mõjuhinnangud iga <span class="math inline">\(X_{k}\)</span> väärtuse korral ning arvutame kaalutud keskmise kasutades kaaludena <span class="math inline">\(X_{k}\)</span> osakaale (nt meeste või naiste osakaale). Kui soovime leida mõju vaid osalejatele (ATT) või mitteosalejatele (ATU), siis vastavalt leiame osakaalud osalejate või mitteosalejate järgi.</p>
</section>
<section id="kaks-eraldi-regressioonimudelit" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="kaks-eraldi-regressioonimudelit"><span class="header-section-number">3.4</span> Kaks eraldi regressioonimudelit</h2>
<p>Ülaltoodud mudel eeldas, et meetmes osalemise mõju varieerub vaid ühe tunnuse lõikes. Paindlikum lähenemine lubab meetmel olla erineva mõjuga kõigi tunnuste lõikes, st me korrutame iga selgitava tunnuse <span class="math inline">\(X\)</span> läbi meetmes osalemise tunnusega <span class="math inline">\(D\)</span>:</p>
<p><span class="math display">\[Y_i = \alpha + \delta D_i + \mathbf{X}_i \beta  + (D_i \cdot \mathbf{X}_{i}) \gamma + \epsilon_i\]</span></p>
<p>See võimaldab heterogeenset funktsionaalset seost <span class="math inline">\(\mathbf{X}\)</span> ja <span class="math inline">\(Y^0\)</span> ning <span class="math inline">\(Y^1\)</span> vahel.</p>
<p>Keskmise mõju leidmiseks taolisest mudelist (nt ATE), peame leidma meetmes osalemise mõju iga vaatluse jaoks ja siis leidma keskmise. Seda saab teha erinevate Ri pakettidega (vt empiirilist näidet allpool).</p>
<p>Interaktsiooniliikme lisamine igale selgitavale tunnusele on tegelikult samaväärne, kui hinnata regressioonimudelid eraldi osalejate (<span class="math inline">\(D=1\)</span>) ja mitteosalejate (<span class="math inline">\(D=0\)</span>) lõikes, sest interaktsiooniga mudelis tulebki iga parameeter erinev osalejatele ja mitteosalejatele. Kahe mudeli hindamine on regressioonimudeliga hindamise kõige paindlikum juht, kuna võimaldab funktsionaalsel seosel <span class="math inline">\(Y \sim \mathbf{X}\)</span> olla erinev osalejatel ja mitteosalejatel.</p>
<ol type="1">
<li><p><strong>Mudel osalejate andmetel</strong> (<span class="math inline">\(D=1\)</span>): <span class="math display">\[Y_i = \alpha_1 + \mathbf{X}_i \beta_1 + \epsilon_{i1} \quad \text{kui } D_i=1\]</span></p>
<p>Prognoosime saadud regressioonimudeli parameetrite abile potentsiaalse tulemuse meetmes osalemise korral <strong>kõigile</strong> vaatlustele: <span class="math inline">\(\hat{Y}^1_{i} = \hat{\alpha}_1 + \mathbf{X}_i \hat{\beta}_1\)</span>.</p></li>
<li><p><strong>Mudel mitteosalejate andmetel</strong> (<span class="math inline">\(D=0\)</span>):</p></li>
</ol>
<p><span class="math display">\[Y_i = \alpha_0 + \mathbf{X}_i \beta_0 + \epsilon_{i0} \quad \text{kui } D_i=0\]</span></p>
<p>Taas prognoosime <strong>kõigile</strong> vaatlustele potentsiaalse tulemuse meetmes mitteosalemise korral : <span class="math inline">\(\hat{Y}^0_{i} = \hat{\alpha}_0 + \mathbf{X}_i \hat{\beta}_0\)</span>.</p>
<ol start="3" type="1">
<li><strong>Mõju arvutamine</strong> : Mõju hinnang iga isiku jaoks on prognoositud potentsiaalsete tulemuste erinevus: <span class="math inline">\(\hat{\Delta}_i = \hat{Y}^1_{i} - \hat{Y}^0_{i}\)</span>. Arvutades välja nende erinevuste keskmised väärtused erinevates rühmades, saame leida meid huvitavad näitajad.
<ul>
<li>ATE (kogu populatsiooni keskmine): <span class="math inline">\(\text{ATE} = \frac{1}{N} \sum_{i=1}^N \hat{\Delta}_i\)</span></li>
<li>ATT (meetmes tegelikult osalejate keskmine): <span class="math inline">\(\text{ATT} = \frac{1}{N_T} \sum_{i: D_i=1} \hat{\Delta}_i\)</span></li>
<li>ATU (võrdlusrühma keskmine, kui nad oleks osalenud): <span class="math inline">\(\text{ATU} = \frac{1}{N_C} \sum_{i: D_i=0} \hat{\Delta}_i\)</span>,</li>
</ul></li>
</ol>
<p>kus <span class="math inline">\(N\)</span>, <span class="math inline">\(N_T\)</span> ja <span class="math inline">\(N_C\)</span> on vastavalt vaatluste arv kokku, osalusrühmas ja võrdlusrühmas.</p>
<p><strong>Standardvigade leidmine</strong></p>
<p>Saadud ATE (või ka ATT, ATU) punkthinnangu standardvea ja usalduspiirid saab leida simulatsioonimeetodi abil (nn <em>bootstrapping</em>). Kui mudelit hinnata interaktsioonidega ühe mudeliga, siis saab marginaalsete efektide leidmisel paketist <em>margins</em> või <em>marginaleffects</em> ka automaatselt standardvead. Vaata näiteid empriilises ülesandes. Paidlik pakett on veel <em>CausalGAM</em> (mis küll seisuga 15.09.2026 ei olnud uuendatud ja see oli arhiveeeritud https://cran-archive.r-project.org/web/checks/2026/2026-04-30_check_results_CausalGAM.html) .</p>
<section id="g-arvutus-g-computation" class="level3">
<h3 class="anchored" data-anchor-id="g-arvutus-g-computation">G-arvutus (<em>G-computation</em>)</h3>
<p>Eelnevat toodud lähemist nimetatakse ka G-arvutuseks (<em>G-computation</em>). See on üldine meetod, kus hindame esmalt tulemusnäitaja sõltuvuse sekkumisest <span class="math inline">\(D\)</span> ja segajatest <span class="math inline">\(X\)</span>. See võib olla regressioonimudel nagu just tegime või ka hoopis paindlikum meetod, näiteks juhumets (<em>random forest</em>), mida vaatame õpiku lõpuosas. Seejärel prognoosime igale inimese tulemuse mõlema sekkumise seisundi korral (<span class="math inline">\(D=1\)</span> ja <span class="math inline">\(D=0\)</span> korral) ning leiame nende prognooside keskmised väärtused sihtpopulatsioonis. Erinevused keskmiste vahel annavadki meile keskmise mõjuhinnangu. (See on tegelikult samaväärne, kui alguses leiame iga inimese jaoks erinevuse ja leiame erinevuste keskmised - nii oligi tehtud ülal).</p>
</section>
</section>
<section id="empiiriline-näide" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="empiiriline-näide"><span class="header-section-number">3.5</span> Empiiriline näide</h2>
<p>Me kasutame näidisandmetena Poliitikauuringute Keskuse Praxis 2002. aastal läbiviidud uuringut aktiivse tööpoliitika mõju hindamise kohta. (Vt Leetmaa, R., Võrk, A., Eamets, R., Sõstra, K. (2003) <em>Aktiivse tööpoliitika tulemuslikkuse analüüs Eestis</em>. Tallinn: Praxis, 108 lk. Vt ka: <a href="https://www.praxis.ee/tood/aktiivse-toopoliitika-tulemuslikkuse-hindamine-eestis/">Praxis töö</a> ja <a href="https://www.researchgate.net/publication/268371718_Evaluation_of_Active_Labour_Market_Programmes_in_Estonia">Leetmaa &amp; Võrk (2004)</a>)</p>
<p>Anonümiseeritud andmestik asub failis:<br>
<a href="http://kodu.ut.ee/~avork/files/oppetoo/micro/atp.csv" class="uri">http://kodu.ut.ee/~avork/files/oppetoo/micro/atp.csv</a></p>
<section id="muutujate-selgitused" class="level3">
<h3 class="anchored" data-anchor-id="muutujate-selgitused">Muutujate selgitused</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 70%">
</colgroup>
<thead>
<tr class="header">
<th>Muutuja</th>
<th>Selgitus</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>training</code></td>
<td>Tunnus kas sai tööturukoolitust või ei 2000. aasta esimeses pooles</td>
</tr>
<tr class="even">
<td><code>nwage</code></td>
<td>Netopalk 2002. aasta septembris. (Tegelikult on tegemist kroonidega, aga all tekstis kasutan sageli eurot)</td>
</tr>
<tr class="odd">
<td><code>employed</code></td>
<td>Hõiveseisund 2002. aasta septembris (1 – hõivatud, 0 – töötu või mitteaktiivne)</td>
</tr>
<tr class="even">
<td><code>status</code></td>
<td>Tööturustaatus 2002. aasta septembris (1 – hõivatud, 2 – töötu, 3 – mitteaktiivne)</td>
</tr>
<tr class="odd">
<td><code>kaal</code></td>
<td>Vaatluse statistiline kaal</td>
</tr>
<tr class="even">
<td><code>male</code></td>
<td>Mees (1), naine (0)</td>
</tr>
<tr class="odd">
<td><code>est</code></td>
<td>Eestlane (1), mitte-eestlane (0)</td>
</tr>
<tr class="even">
<td><code>age</code></td>
<td>Vanus aastates 2002. aastal</td>
</tr>
<tr class="odd">
<td><code>langest</code></td>
<td>Kas oskab eesti keelt? (1 - oskab, 0 - ei oska)</td>
</tr>
<tr class="even">
<td><code>emplbefore</code></td>
<td>Kas oli töökogemus enne töötuks registreerimist 2000. aastal? (1 - oli, 0 - ei olnud)</td>
</tr>
<tr class="odd">
<td><code>educ</code></td>
<td>Haridustase: 1 – ISCED 0,1,2 (põhiharidus); 2 – ISCED 3 (keskharidus); 3 – ISCED 3,4 (kutsekeskharidus); 4 – ISCED 5,6 (kõrgharidus)</td>
</tr>
<tr class="even">
<td><code>county</code></td>
<td>Maakond: Tallinn, Viljandimaa, Tartumaa, Ida-Virumaa</td>
</tr>
<tr class="odd">
<td><code>town</code></td>
<td>Elab linnas (1) või maal (0)</td>
</tr>
<tr class="even">
<td><code>children</code></td>
<td>Laste arv töötuks registreerimise hetkel</td>
</tr>
<tr class="odd">
<td><code>marital</code></td>
<td>Perekonna seis töötuks registreerimise hetkel: 0 – vallaline; 1 – abielus; 2 – vabaabielu; 3 – lahutatud; 4 – lesk</td>
</tr>
<tr class="even">
<td><code>training1</code></td>
<td>Osalusrühm tingimusel, et ei nõutud tõendit hilisema töö saamise kohta – kellelt nõuti, neil puuduv väärtus</td>
</tr>
<tr class="odd">
<td><code>training2</code></td>
<td>Võrdlusgrupp, kes soovisid, kuid ei saanud/soovinud osaleda mingil põhjusel</td>
</tr>
<tr class="even">
<td><code>training3</code></td>
<td>Kombinatsioon training2 ja training3: need osalusgrupist, kellelt ei nõutud töökohta; need võrdlusgrupist, kes uurisid koolitust, kuid ei osalenud</td>
</tr>
<tr class="odd">
<td><code>training4</code></td>
<td>Koolituse osalusrühmas ja võrdlusrühmas mõlemas ainult need, kes ise uurisid</td>
</tr>
<tr class="even">
<td><code>training5</code></td>
<td>Koolituse põhirühmas ja võrdlusrühmas mõlemas ainult need, kes ise uurisid ja kellelt ei nõutud tõendit</td>
</tr>
</tbody>
</table>
</section>
<section id="vajalikud-paketid" class="level3">
<h3 class="anchored" data-anchor-id="vajalikud-paketid">Vajalikud paketid</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co">#andmete teisendamine</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer) <span class="co">#tulemuste esitamine - võimalus 1</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary) <span class="co">#tulemuste esitamine - võimalus 2</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest) <span class="co">#coeftest käsu jaoks, et esitada robustsete standardvigadega - võimalus 1</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich) <span class="co">#robustsed standardvead  - võimalus 1</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest) <span class="co">#hindab lineaarse mudeli, lubab kohe robustseid standardvigu - võimalus 2</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(margins)  <span class="co">#saab leida interkatsioonidega mudelist osamõjud, nt ATE - võimalus 1</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects) <span class="co">#saab leida interkatsioonidega mudelist osamõjud, nt ATE - võimalus 2</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot) <span class="co">#bootstrappinguks, leidmaks simulatsiooniga usalduspiirid</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co">#joonistamiseks</span></span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="andmestiku-lugemine" class="level3">
<h3 class="anchored" data-anchor-id="andmestiku-lugemine">Andmestiku lugemine</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>atp <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"http://kodu.ut.ee/~avork/files/oppetoo/micro/atp.csv"</span>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="kirjeldav-analüüs" class="level3">
<h3 class="anchored" data-anchor-id="kirjeldav-analüüs">Kirjeldav analüüs</h3>
<p>Leidke, mitu inimestest osales 2000. aastal koolituses ja mitu ei osalenud.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(atp<span class="sc">$</span>training)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
878 429 </code></pre>
</div>
</div>
<p>Meetmes osales 429 inimest ja ei osalenud 878 inimest.</p>
<p>Kui suur osakaal koolituses osalejatest ja mitteosalejatest töötas 2002. aasta septembris? Tabuleerige muutujad “training” ja “employed” ning leidke protsendid.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="st">"training"</span><span class="ot">=</span> atp<span class="sc">$</span>training, <span class="st">"employed"</span> <span class="ot">=</span> atp<span class="sc">$</span>employed)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(tab, <span class="at">margin =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        employed
training         0         1
       0 0.4100228 0.5899772
       1 0.2913753 0.7086247</code></pre>
</div>
</div>
<p>Meetmes osalejate seas (training = 1) on pärast töötavaid inimesi 70.9 protsenti ja mitteosalejate seas (training = 0) on 59.0 protsenti. Seega on lihtne erinevus (<em>SDO</em>) 11.9 protsendipunkti.</p>
<p>Milline oli keskmine palk koolituses osalejatel ja mitteosalejatel 2002. aasta septembris?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>atp <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(training) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">mean_wage =</span> <span class="fu">mean</span>(nwage, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  training mean_wage
     &lt;int&gt;     &lt;dbl&gt;
1        0     1678.
2        1     2042.</code></pre>
</div>
</div>
<p>Pangem tähele, et keskmine võtab arvesse ka mittetöötavad inimesed ja paneb nende palga võrdseks nulliga. Kuidas leida palga erinevus ainult töötavate inimeste jaoks?</p>
</section>
<section id="regressioonimudel" class="level3">
<h3 class="anchored" data-anchor-id="regressioonimudel">Regressioonimudel</h3>
<p>Hinnake regressioonimudel, kus väljundid <em>employed</em> ja <em>nwage</em> sõltuvad ainult koolituses osalemisest.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(employed <span class="sc">~</span> training, <span class="at">data =</span> atp)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(nwage <span class="sc">~</span> training, <span class="at">data =</span> atp)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(m1, m2, <span class="at">type =</span> <span class="st">"text"</span>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================================
                                  Dependent variable:               
                    ------------------------------------------------
                            employed                  nwage         
                              (1)                      (2)          
--------------------------------------------------------------------
training                    0.119***               363.850***       
                            (0.028)                 (119.754)       
                                                                    
Constant                    0.590***              1,677.766***      
                            (0.016)                 (68.337)        
                                                                    
--------------------------------------------------------------------
Observations                 1,307                    1,256         
R2                           0.013                    0.007         
Adjusted R2                  0.013                    0.007         
Residual Std. Error    0.480 (df = 1305)      1,988.834 (df = 1254) 
F Statistic         17.591*** (df = 1; 1305) 9.231*** (df = 1; 1254)
====================================================================
Note:                                    *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>Saadud regressioonimudel annab muidugi sama tulemuse kui ülal leitud keskmiste erinevus käsitsi arvutatuna.</p>
<p>Siit saame aga mugavalt edasi minna ja hinnata mudelid koos teiste selgitavate teguritega. Lubame kohe ka vealiikme heteroskedastiivsust. Lubame ka vanuse ruutliiget, et võtta arvesse vanuse võimalik mittelineaarne seos töötamise tõenäousega ja palgaga.</p>
<p>NB! Pangem tähele, et meie uuritav tunnus on tegelikult binaarne (1-0) ja võiksime hinnata ka logit- või probit-mudeli. Praktikas tulevad keskmised mõjuhinnangud (ATE, ATT, ATU) lineaarsest mudelist ja logit- või probit-mudelist väga sarnased.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>atp<span class="sc">$</span>age2 <span class="ot">&lt;-</span> atp<span class="sc">$</span>age<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>lin_employed <span class="ot">&lt;-</span> <span class="fu">lm</span>(employed <span class="sc">~</span> training <span class="sc">+</span> male <span class="sc">+</span> est <span class="sc">+</span> age <span class="sc">+</span> age2 <span class="sc">+</span> educ <span class="sc">+</span> emplbefore, <span class="at">data =</span> atp)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(lin_employed, <span class="at">vcov =</span> <span class="fu">vcovHC</span>(lin_employed, <span class="st">"HC1"</span>))</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

               Estimate  Std. Error t value  Pr(&gt;|t|)    
(Intercept) -0.15070176  0.15151587 -0.9946 0.3201030    
training     0.09816437  0.02764834  3.5505 0.0003983 ***
male         0.07986481  0.02872120  2.7807 0.0055027 ** 
est          0.09711124  0.02694719  3.6038 0.0003255 ***
age          0.02945808  0.00978750  3.0098 0.0026649 ** 
age2        -0.00040217  0.00012743 -3.1560 0.0016364 ** 
educ         0.05265150  0.01496051  3.5194 0.0004475 ***
emplbefore   0.05064137  0.05218072  0.9705 0.3319782    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Näeme, et tööturukoolituses osalejatel on peale teiste tunnuste mõju arvesse võtmist 0.098 ehk 9.8 protsendipunkti suurem tõenäosus hiljem töötada kui koolituses mitteosalejatel.</p>
<p>Tõlgendage ka teiste selgitavate tunnuste kordajaid. Kuidas tõlgendada vanuse mõju?</p>
<p>Hinnakem samasugune mudel ka palga kohta.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>lin_nwage <span class="ot">&lt;-</span> <span class="fu">lm</span>(nwage <span class="sc">~</span> training <span class="sc">+</span> male <span class="sc">+</span> est <span class="sc">+</span> age <span class="sc">+</span> age2 <span class="sc">+</span> educ <span class="sc">+</span> emplbefore, <span class="at">data =</span> atp)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(lin_nwage, <span class="at">vcov =</span> <span class="fu">vcovHC</span>(lin_nwage, <span class="st">"HC1"</span>))</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

               Estimate  Std. Error t value  Pr(&gt;|t|)    
(Intercept) -1284.89226   687.88260 -1.8679   0.06201 .  
training      254.84877   111.15732  2.2927   0.02203 *  
male          871.32268   138.00166  6.3139 3.775e-10 ***
est           821.63833   127.20240  6.4593 1.504e-10 ***
age            82.57500    43.00273  1.9202   0.05506 .  
age2           -1.33722     0.53949 -2.4786   0.01332 *  
educ          297.93783    61.36353  4.8553 1.354e-06 ***
emplbefore    540.05556   220.40577  2.4503   0.01441 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Meetmes osalejate palk on pärast meedet keskmiselt 255 euro võrra suurem kui meetmes mitteosalejatel.</p>
<p>Tavapäraselt esitame taolised regressioonimudelid kompaktselt koos ühes tabelis. Seda saab teha näiteks paketiga <em>stargazer</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>robust_se1 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(lin_employed, <span class="at">type =</span> <span class="st">"HC1"</span>)))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>robust_se2 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(lin_nwage, <span class="at">type =</span> <span class="st">"HC1"</span>)))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(lin_employed, lin_nwage, <span class="at">se =</span> <span class="fu">list</span>(robust_se1, robust_se2), <span class="at">type =</span> <span class="st">"text"</span>, <span class="at">no.space =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
====================================================================
                                  Dependent variable:               
                    ------------------------------------------------
                           employed                  nwage          
                              (1)                     (2)           
--------------------------------------------------------------------
training                   0.098***                254.849**        
                            (0.028)                (111.157)        
male                       0.080***                871.323***       
                            (0.029)                (138.002)        
est                        0.097***                821.638***       
                            (0.027)                (127.202)        
age                        0.029***                 82.575*         
                            (0.010)                 (43.003)        
age2                      -0.0004***                -1.337**        
                           (0.0001)                 (0.539)         
educ                       0.053***                297.938***       
                            (0.015)                 (61.364)        
emplbefore                   0.051                 540.056**        
                            (0.052)                (220.406)        
Constant                    -0.151                -1,284.892*       
                            (0.152)                (687.883)        
--------------------------------------------------------------------
Observations                 1,307                   1,256          
R2                           0.051                   0.109          
Adjusted R2                  0.046                   0.104          
Residual Std. Error    0.472 (df = 1299)     1,888.387 (df = 1248)  
F Statistic         9.954*** (df = 7; 1299) 21.885*** (df = 7; 1248)
====================================================================
Note:                                    *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>Kõrvalepõikena, pakett <em>fixest</em> sisaldab käsku <em>feols</em>, mis laseb kohe esitada ka robustsed standardvead. Pakett <em>modelsummary</em> esitab need. Millist paketti kasutada on maitse asi.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>lin_employedrob <span class="ot">&lt;-</span> <span class="fu">feols</span>(employed <span class="sc">~</span> training <span class="sc">+</span> male <span class="sc">+</span> est<span class="sc">+</span> age <span class="sc">+</span> age2  <span class="sc">+</span> educ <span class="sc">+</span> emplbefore, <span class="at">data=</span>atp, <span class="at">vcov =</span> <span class="st">"HC1"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>lin_nwagerob <span class="ot">&lt;-</span> <span class="fu">feols</span>(nwage <span class="sc">~</span> training <span class="sc">+</span> male <span class="sc">+</span> est<span class="sc">+</span> age <span class="sc">+</span> age2  <span class="sc">+</span> educ <span class="sc">+</span> emplbefore, <span class="at">data=</span>atp, <span class="at">vcov =</span> <span class="st">"HC1"</span>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>NOTE: 51 observations removed because of NA values (LHS: 51).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(<span class="at">models =</span> <span class="fu">list</span>(lin_employedrob, lin_nwagerob), </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">estimate =</span> <span class="st">"{estimate} {stars}"</span>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_imhcprf1dz7thfcd0ynv = TinyTable.createTableFunctions("tinytable_imhcprf1dz7thfcd0ynv");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '23', j: 2 }, { i: '23', j: 3 } ], css_id: 'tinytable_css_3gzmk25ikahwn6mjc0d6',}, 
          { positions: [ { i: '16', j: 2 }, { i: '16', j: 3 } ], css_id: 'tinytable_css_w0nq2nw71ke419cv481h',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '17', j: 2 }, { i: '18', j: 2 }, { i: '19', j: 2 }, { i: '20', j: 2 }, { i: '21', j: 2 }, { i: '22', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '17', j: 3 }, { i: '18', j: 3 }, { i: '19', j: 3 }, { i: '20', j: 3 }, { i: '21', j: 3 }, { i: '22', j: 3 } ], css_id: 'tinytable_css_e7u6naobdqn5z9qijfwr',}, 
          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_o8fz2arzb9j1hvlqgs7t',}, 
          { positions: [ { i: '23', j: 1 } ], css_id: 'tinytable_css_0spjpejoekjft7njyhpc',}, 
          { positions: [ { i: '16', j: 1 } ], css_id: 'tinytable_css_v2xxx1afjalj5ceocefd',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '17', j: 1 }, { i: '18', j: 1 }, { i: '19', j: 1 }, { i: '20', j: 1 }, { i: '21', j: 1 }, { i: '22', j: 1 } ], css_id: 'tinytable_css_k2zmblmttbpu08ye8wuq',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_nnsau5aeixc49pj3980q',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_imhcprf1dz7thfcd0ynv.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_imhcprf1dz7thfcd0ynv td.tinytable_css_3gzmk25ikahwn6mjc0d6, #tinytable_imhcprf1dz7thfcd0ynv th.tinytable_css_3gzmk25ikahwn6mjc0d6 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_imhcprf1dz7thfcd0ynv td.tinytable_css_w0nq2nw71ke419cv481h, #tinytable_imhcprf1dz7thfcd0ynv th.tinytable_css_w0nq2nw71ke419cv481h {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_imhcprf1dz7thfcd0ynv td.tinytable_css_e7u6naobdqn5z9qijfwr, #tinytable_imhcprf1dz7thfcd0ynv th.tinytable_css_e7u6naobdqn5z9qijfwr { text-align: center }
    #tinytable_imhcprf1dz7thfcd0ynv td.tinytable_css_o8fz2arzb9j1hvlqgs7t, #tinytable_imhcprf1dz7thfcd0ynv th.tinytable_css_o8fz2arzb9j1hvlqgs7t {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_imhcprf1dz7thfcd0ynv td.tinytable_css_0spjpejoekjft7njyhpc, #tinytable_imhcprf1dz7thfcd0ynv th.tinytable_css_0spjpejoekjft7njyhpc {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_imhcprf1dz7thfcd0ynv td.tinytable_css_v2xxx1afjalj5ceocefd, #tinytable_imhcprf1dz7thfcd0ynv th.tinytable_css_v2xxx1afjalj5ceocefd {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_imhcprf1dz7thfcd0ynv td.tinytable_css_k2zmblmttbpu08ye8wuq, #tinytable_imhcprf1dz7thfcd0ynv th.tinytable_css_k2zmblmttbpu08ye8wuq { text-align: left }
    #tinytable_imhcprf1dz7thfcd0ynv td.tinytable_css_nnsau5aeixc49pj3980q, #tinytable_imhcprf1dz7thfcd0ynv th.tinytable_css_nnsau5aeixc49pj3980q {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: black; --line-color-left: black; --line-color-right: black; --line-color-top: black; --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_imhcprf1dz7thfcd0ynv" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">(1)</th>
                <th scope="col" data-row="0" data-col="3">(2)</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">(Intercept)</td>
                  <td data-row="1" data-col="2">-0.151</td>
                  <td data-row="1" data-col="3">-1284.892 +</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.152)</td>
                  <td data-row="2" data-col="3">(687.883)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">training</td>
                  <td data-row="3" data-col="2">0.098 ***</td>
                  <td data-row="3" data-col="3">254.849 *</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.028)</td>
                  <td data-row="4" data-col="3">(111.157)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">male</td>
                  <td data-row="5" data-col="2">0.080 **</td>
                  <td data-row="5" data-col="3">871.323 ***</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.029)</td>
                  <td data-row="6" data-col="3">(138.002)</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">est</td>
                  <td data-row="7" data-col="2">0.097 ***</td>
                  <td data-row="7" data-col="3">821.638 ***</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2">(0.027)</td>
                  <td data-row="8" data-col="3">(127.202)</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">age</td>
                  <td data-row="9" data-col="2">0.029 **</td>
                  <td data-row="9" data-col="3">82.575 +</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1"></td>
                  <td data-row="10" data-col="2">(0.010)</td>
                  <td data-row="10" data-col="3">(43.003)</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">age2</td>
                  <td data-row="11" data-col="2">-0.000 **</td>
                  <td data-row="11" data-col="3">-1.337 *</td>
                </tr>
                <tr>
                  <td data-row="12" data-col="1"></td>
                  <td data-row="12" data-col="2">(0.000)</td>
                  <td data-row="12" data-col="3">(0.539)</td>
                </tr>
                <tr>
                  <td data-row="13" data-col="1">educ</td>
                  <td data-row="13" data-col="2">0.053 ***</td>
                  <td data-row="13" data-col="3">297.938 ***</td>
                </tr>
                <tr>
                  <td data-row="14" data-col="1"></td>
                  <td data-row="14" data-col="2">(0.015)</td>
                  <td data-row="14" data-col="3">(61.364)</td>
                </tr>
                <tr>
                  <td data-row="15" data-col="1">emplbefore</td>
                  <td data-row="15" data-col="2">0.051</td>
                  <td data-row="15" data-col="3">540.056 *</td>
                </tr>
                <tr>
                  <td data-row="16" data-col="1"></td>
                  <td data-row="16" data-col="2">(0.052)</td>
                  <td data-row="16" data-col="3">(220.406)</td>
                </tr>
                <tr>
                  <td data-row="17" data-col="1">Num.Obs.</td>
                  <td data-row="17" data-col="2">1307</td>
                  <td data-row="17" data-col="3">1256</td>
                </tr>
                <tr>
                  <td data-row="18" data-col="1">R2</td>
                  <td data-row="18" data-col="2">0.051</td>
                  <td data-row="18" data-col="3">0.109</td>
                </tr>
                <tr>
                  <td data-row="19" data-col="1">R2 Adj.</td>
                  <td data-row="19" data-col="2">0.046</td>
                  <td data-row="19" data-col="3">0.104</td>
                </tr>
                <tr>
                  <td data-row="20" data-col="1">AIC</td>
                  <td data-row="20" data-col="2">1755.0</td>
                  <td data-row="20" data-col="3">22521.6</td>
                </tr>
                <tr>
                  <td data-row="21" data-col="1">BIC</td>
                  <td data-row="21" data-col="2">1796.4</td>
                  <td data-row="21" data-col="3">22562.7</td>
                </tr>
                <tr>
                  <td data-row="22" data-col="1">RMSE</td>
                  <td data-row="22" data-col="2">0.47</td>
                  <td data-row="22" data-col="3">1882.36</td>
                </tr>
                <tr>
                  <td data-row="23" data-col="1">Std.Errors</td>
                  <td data-row="23" data-col="2">Heteroskedasticity-robust</td>
                  <td data-row="23" data-col="3">Heteroskedasticity-robust</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
</section>
<section id="eraldi-mudelid-osalejatele-ja-mitteosalejatele" class="level3">
<h3 class="anchored" data-anchor-id="eraldi-mudelid-osalejatele-ja-mitteosalejatele">Eraldi mudelid osalejatele ja mitteosalejatele</h3>
<p><strong>Ühe tunnusega mudel</strong></p>
<p>Järgnevalt lubame meetme mõjul erineda erinevates sotsiaaldemograafilistes rühmades. Alguses vaatame mõju palgale lubades vaid vanuse erinevat mõju, et saaksime illustreerida tulemusi joonisel. Piirame ajutiselt palka ülalt ja vaatame vaid mitte nulle.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>atpj <span class="ot">&lt;-</span> atp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(nwage)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(nwage<span class="sc">&lt;</span><span class="dv">5000</span>, nwage<span class="sc">&gt;</span><span class="dv">0</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>mudelvanus <span class="ot">&lt;-</span> <span class="fu">lm</span>(nwage <span class="sc">~</span> age<span class="sc">*</span>training, <span class="at">data =</span> atpj)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mudelvanus)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = nwage ~ age * training, data = atpj)

Residuals:
    Min      1Q  Median      3Q     Max 
-2688.4  -690.8  -160.4   620.3  2413.5 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2632.984    157.919  16.673   &lt;2e-16 ***
age            -6.537      4.208  -1.553    0.121    
training      368.920    264.198   1.396    0.163    
age:training   -5.895      7.181  -0.821    0.412    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 933 on 674 degrees of freedom
Multiple R-squared:  0.01776,   Adjusted R-squared:  0.01338 
F-statistic: 4.061 on 3 and 674 DF,  p-value: 0.007099</code></pre>
</div>
</div>
<p>Näeme, et koolituse mõju on positiivne (369 eurot), aga iga aasta, mis vanusele juurde tuleb, vähendab koolituse mõju 5.9 euro võrra. (Tõsi, ükski kumbki parameeter ei ole statistiliselt oluline.)</p>
<p>Illustreerime tulemust ka joonisel.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(atpj, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> nwage, <span class="at">color =</span> <span class="st">"Palk"</span>)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> atpj <span class="sc">%&gt;%</span> <span class="fu">filter</span>(training <span class="sc">==</span><span class="dv">1</span>), <span class="at">method =</span> <span class="st">"lm"</span>, </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>, </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">color =</span> <span class="st">"Prognoos, D = 1"</span>)) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> atpj <span class="sc">%&gt;%</span> <span class="fu">filter</span>(training <span class="sc">==</span><span class="dv">0</span>), <span class="at">method =</span> <span class="st">"lm"</span>, </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>, </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">color =</span> <span class="st">"Prognoos, D = 0"</span>)) <span class="sc">+</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">""</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Palk"</span> <span class="ot">=</span> <span class="st">"grey"</span>,</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>                                           <span class="st">"Prognoos, D = 1"</span> <span class="ot">=</span> <span class="st">"blue"</span>,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>                                           <span class="st">"Prognoos, D = 0"</span> <span class="ot">=</span> <span class="st">"green"</span>)) <span class="sc">+</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Vanus"</span>, <span class="at">y =</span> <span class="st">"Palk"</span>, <span class="at">color =</span> <span class="st">""</span>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-regressioon_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Salvestame ka prognoositud väärtuste erinevuse järgmise joonise jaoks</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>atpj<span class="sc">$</span>ate <span class="ot">&lt;-</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(<span class="fu">lm</span>(nwage <span class="sc">~</span> age, <span class="at">data=</span>atpj[atpj<span class="sc">$</span>training<span class="sc">==</span><span class="dv">1</span>,]), <span class="at">new=</span>atpj) <span class="sc">-</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>           <span class="fu">predict</span>(<span class="fu">lm</span>(nwage <span class="sc">~</span> age, <span class="at">data=</span>atpj[atpj<span class="sc">$</span>training<span class="sc">==</span><span class="dv">0</span>,]), <span class="at">new=</span>atpj)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Joonis näitab, et vanus mõjutab palka osalejate ja mitteosalejate seas erinevalt. Mida noorem on inimene, seda suurem on joontevaheline erinevus ehk meetmes osalemise mõju on suurem. Esitame selle erinevuse eraldi joonisel, lisame vaatluste jaotuse väikese histogrammina X-teljel.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(atpj,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> ate)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">as.factor</span>(training), <span class="at">y =</span> ..count..), </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">position =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"green"</span>, <span class="st">"blue"</span>)) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Vanus"</span>, <span class="at">y =</span> <span class="st">"Meetme mõju"</span>, <span class="at">fill =</span> <span class="st">"Meetmes"</span>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(count)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-regressioon_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Täielik interaktsioon</strong></p>
<p>Lisame järgnevalt mudelisse kõik ülejäänud selgitavad tunnused. Viime läbi G-arvutuse töötamise väljundi jaoks.</p>
<p>Esimene samm: hindame mudeli osalejate andmete põhjal <em>training==1</em> ja prognoosime tulemused kõigile.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>lin_employed_ra1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(employed <span class="sc">~</span> male <span class="sc">+</span> est <span class="sc">+</span> age <span class="sc">+</span> age2 <span class="sc">+</span> educ <span class="sc">+</span> emplbefore, <span class="at">data =</span> atp[atp<span class="sc">$</span>training <span class="sc">==</span> <span class="dv">1</span>, ])</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>atp<span class="sc">$</span>pemployed_1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lin_employed_ra1, <span class="at">newdata =</span> atp)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Teine samm: hindame samasuguse mudeli ka mitteosalejate põhjal <em>training==0</em> ja prognoosime tulemused kõigile</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>lin_employed_ra0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(employed <span class="sc">~</span> male <span class="sc">+</span> est <span class="sc">+</span> age <span class="sc">+</span> age2 <span class="sc">+</span> educ <span class="sc">+</span> emplbefore, <span class="at">data =</span> atp[atp<span class="sc">$</span>training <span class="sc">==</span> <span class="dv">0</span>, ])</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>atp<span class="sc">$</span>pemployed_0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lin_employed_ra0, <span class="at">newdata =</span> atp)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Kolmas samm: leiame individuaalsed erinevused prognoositud hinnangutes</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>atp<span class="sc">$</span>demployed <span class="ot">&lt;-</span> atp<span class="sc">$</span>pemployed_1 <span class="sc">-</span> atp<span class="sc">$</span>pemployed_0</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Neljas samm: Leiame keskmised mõjuhinnangud (ATE) ja eraldi ka osalejatele (ATT) ning mitteosalejatele (ATU).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>ate_empl <span class="ot">&lt;-</span> <span class="fu">mean</span>(atp<span class="sc">$</span>demployed)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>att_empl <span class="ot">&lt;-</span> <span class="fu">mean</span>(atp<span class="sc">$</span>demployed[atp<span class="sc">$</span>training <span class="sc">==</span> <span class="dv">1</span>])</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>atu_empl <span class="ot">&lt;-</span> <span class="fu">mean</span>(atp<span class="sc">$</span>demployed[atp<span class="sc">$</span>training <span class="sc">==</span> <span class="dv">0</span>])</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>ate_empl</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1063243</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>att_empl</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0926108</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>atu_empl</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1130248</code></pre>
</div>
</div>
<p>Näeme, et paindlikuma mudeli järgi tuli meetme keskmine mõju (ATE) pisut suurem. Enne oli 9.8 protsendipunkti, nüüd 10.6 protsendipunkti. Näeme ka, et meetme mõju oleks olnud suurem mitteosalejatele (ATU = 0.113) kui osalejatele (ATT = 0.093). See tähendab, et millegipärast sattusid tööturukoolitusele vähem need inimesed, kellel sellest oleks rohkem kasu olnud. Võimalik, et tegu on näiteks koore riisumisega. (Selle hindamiseks on andmestikus olemas tegelikult täiendavad tunnused training1, training2 jne, millega võite huvi korral ise analüüsi teha.)</p>
<p><strong>Mõju palgale</strong> leiame analoogselt:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>lin_nwage_ra1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(nwage <span class="sc">~</span> male <span class="sc">+</span> est <span class="sc">+</span> age <span class="sc">+</span> age2 <span class="sc">+</span> educ <span class="sc">+</span> emplbefore, <span class="at">data =</span> atp[atp<span class="sc">$</span>training <span class="sc">==</span> <span class="dv">1</span>, ])</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>atp<span class="sc">$</span>nwage_1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lin_nwage_ra1, <span class="at">newdata =</span> atp)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>lin_nwage_ra0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(nwage <span class="sc">~</span> male <span class="sc">+</span> est <span class="sc">+</span> age <span class="sc">+</span> age2 <span class="sc">+</span> educ <span class="sc">+</span> emplbefore, <span class="at">data =</span> atp[atp<span class="sc">$</span>training <span class="sc">==</span> <span class="dv">0</span>, ])</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>atp<span class="sc">$</span>nwage_0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lin_nwage_ra0, <span class="at">newdata =</span> atp)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>atp<span class="sc">$</span>dnwage <span class="ot">&lt;-</span> atp<span class="sc">$</span>nwage_1 <span class="sc">-</span> atp<span class="sc">$</span>nwage_0</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>ate_nwage <span class="ot">&lt;-</span> <span class="fu">mean</span>(atp<span class="sc">$</span>dnwage)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>att_nwage <span class="ot">&lt;-</span> <span class="fu">mean</span>(atp<span class="sc">$</span>dnwage[atp<span class="sc">$</span>training <span class="sc">==</span> <span class="dv">1</span>])</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>atu_nwage <span class="ot">&lt;-</span> <span class="fu">mean</span>(atp<span class="sc">$</span>dnwage[atp<span class="sc">$</span>training <span class="sc">==</span> <span class="dv">0</span>])</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>ate_nwage</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 259.2266</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>att_nwage</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 254.2755</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>atu_nwage</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 261.6458</code></pre>
</div>
</div>
<p>Kas koolituse mõju on suurem osalejatele või oleks olnud suurem mitteosalejatele?</p>
</section>
<section id="usalduspiiride-leidmine" class="level3">
<h3 class="anchored" data-anchor-id="usalduspiiride-leidmine">Usalduspiiride leidmine</h3>
<p>Kui soovime leida usalduspiirid ATE, ATT ja ATU jaoks võime kasutada kas analüütilisi lähenemisi või simuleeritud viise. Vaatame esmalt paketti <em>margins</em>. Hindame mudeli interaktsiooniefektiga kõigi tunnuste ja meetmes osalemise vahel. See on täpselt sama, kui oleksime hinnanud kaks eraldi mudelit.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>intmudel <span class="ot">&lt;-</span> <span class="fu">lm</span>(employed <span class="sc">~</span> (male <span class="sc">+</span> est <span class="sc">+</span> age <span class="sc">+</span> age2 <span class="sc">+</span> educ <span class="sc">+</span> emplbefore)<span class="sc">*</span>training, <span class="at">data =</span> atp)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(intmudel)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = employed ~ (male + est + age + age2 + educ + emplbefore) * 
    training, data = atp)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.8805 -0.5394  0.2637  0.3650  0.7429 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         -0.3667782  0.1809040  -2.027 0.042819 *  
male                 0.0744352  0.0341843   2.177 0.029626 *  
est                  0.0948953  0.0333345   2.847 0.004487 ** 
age                  0.0416228  0.0116071   3.586 0.000348 ***
age2                -0.0005708  0.0001498  -3.810 0.000146 ***
educ                 0.0618809  0.0179495   3.447 0.000584 ***
emplbefore           0.0452292  0.0636602   0.710 0.477536    
training             0.8729799  0.3349351   2.606 0.009255 ** 
male:training        0.0114457  0.0630477   0.182 0.855972    
est:training         0.0090808  0.0578150   0.157 0.875217    
age:training        -0.0450855  0.0214787  -2.099 0.036003 *  
age2:training        0.0006390  0.0002819   2.267 0.023580 *  
educ:training       -0.0301854  0.0321101  -0.940 0.347363    
emplbefore:training  0.0352448  0.1091517   0.323 0.746825    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4717 on 1293 degrees of freedom
Multiple R-squared:  0.05697,   Adjusted R-squared:  0.04749 
F-statistic: 6.009 on 13 and 1293 DF,  p-value: 5.768e-11</code></pre>
</div>
</div>
<p>Leiame nüüd muutuja <em>training</em> keskmise mõju terves valimis käsuga <em>margins</em>. Saame sellega ATE hinnangu. Selle käsu pluss on see, et saame ka ligilähedased standardvead, mida pakett <em>margins</em> hindab delta-meetodiga (<em>AV</em> <em>endale: täpsusta metoodikat</em>)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(margins)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">margins</span>(intmudel, <span class="at">variables =</span> <span class="st">"training"</span>))</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   factor    AME     SE      z      p  lower  upper
 training 0.1063 0.0284 3.7399 0.0002 0.0506 0.1620</code></pre>
</div>
</div>
<p>Saame sama punkthinnangu, mis ülal. Meetme keskmine mõju on 10.63 protsendipunkti. Nüüd on lisatud ka usalduspiirid, kust näeme, et 95%line usaldusvahemik on 5.06 - 16.2 protsendipunkti. Hinnang on ka statistiliselt oluline (p = 0.0002).</p>
<p>Sama teeb ka käsk <em>avg_comparisons</em> paketist <em>marginaleffects</em>. Siin saame lubada kohe ka robustseid standardvigu.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_comparisons</span>(intmudel, <span class="at">variables =</span> <span class="st">"training"</span>, <span class="at">vcov =</span> <span class="st">"HC1"</span>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error    z Pr(&gt;|z|)    S  2.5 % 97.5 %
    0.106     0.0278 3.82   &lt;0.001 12.9 0.0518  0.161

Term: training
Type: response
Comparison: 1 - 0</code></pre>
</div>
</div>
<p>Saame sarnaselt leida ka ATT, kui paneme andmetele peale tingimuse, et <em>training</em> ==1.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">margins</span>(intmudel, <span class="at">variables =</span> <span class="st">"training"</span>, <span class="at">data =</span> atp[atp<span class="sc">$</span>training <span class="sc">==</span><span class="dv">1</span>,]))</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   factor    AME     SE      z      p  lower  upper
 training 0.0926 0.0283 3.2750 0.0011 0.0372 0.1480</code></pre>
</div>
</div>
<p>Veenduge, et saate sama tulemuse, mis ülal.</p>
<p>Viimaks, leiame D mõju alamvalimis, kui training == 0, millega saame ATU.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">margins</span>(intmudel, <span class="at">variables =</span> <span class="st">"training"</span>, <span class="at">data =</span> atp[atp<span class="sc">$</span>training <span class="sc">==</span><span class="dv">0</span>,]))</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   factor    AME     SE      z      p  lower  upper
 training 0.1130 0.0291 3.8864 0.0001 0.0560 0.1700</code></pre>
</div>
</div>
</section>
<section id="bootstrapping-hinnangute-standardvea-leidmiseks---fännidele" class="level3">
<h3 class="anchored" data-anchor-id="bootstrapping-hinnangute-standardvea-leidmiseks---fännidele">Bootstrapping hinnangute standardvea leidmiseks - fännidele</h3>
<p>Üldjuhul võib esimesel sammul leitud mudelid olla keerulisemad ja taoline käsk <em>margins</em> ei ole rakendatav. Sellisel juhul võib alati kasutada ka simulatsioonimeetodit ehk bootstrappingut.</p>
<p>Teeme esmalt funktsiooni, mida me soovime hinnata. Vaatame esmalt mõju töötamisele. Selleks hindame töötamise mudeli osalus ja võrdlusrühmas, prognoosime kohe mudelist väärtused ja leiame prognooside erinevused. Allolevas funktsioonis on sisendiks andmestik <em>dat</em>, mis muutub.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">formula</span>(employed <span class="sc">~</span> male <span class="sc">+</span> est <span class="sc">+</span> age <span class="sc">+</span> age2 <span class="sc">+</span> educ <span class="sc">+</span> emplbefore)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>mybs <span class="ot">=</span> <span class="cf">function</span>(data, indices, <span class="at">formula =</span>f) {</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  dat <span class="ot">=</span> data[indices, ]</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  dify <span class="ot">=</span> <span class="fu">predict</span>(<span class="fu">lm</span>(formula, <span class="at">data =</span> dat[dat<span class="sc">$</span>training <span class="sc">==</span> <span class="dv">1</span>, ]), <span class="at">newdata =</span> dat) <span class="sc">-</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>         <span class="fu">predict</span>(<span class="fu">lm</span>(formula, <span class="at">data =</span> dat[dat<span class="sc">$</span>training <span class="sc">==</span> <span class="dv">0</span>, ]), <span class="at">newdata =</span> dat)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">ate =</span> <span class="fu">mean</span>(dify), <span class="at">att =</span> <span class="fu">mean</span>(dify[dat<span class="sc">$</span>training <span class="sc">==</span> <span class="dv">1</span>]))</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Kui funktsioon on valmis rakendame seda andmestikule <em>dat</em>, mis moodustatakse juhuslikult võttes tagasipanekuga valimeid meie algsest andmestikust. Iga taolise uue kunstliku andmestiku korral hinnatakse meid huvitavad parameetrid (meie puhul ATE ja ATT). Võttes niimoodi suure arvu valimeid, leiame meie parameetrite jaotuse, usalduspiirid ja standardvea. Saadud usalduspiire kasutame ülalleitud parameetrite (ATE, ATT) jaoks.</p>
<p>Alljärgnev käsk viib läbi simulatsiooni. NB! Praegu on kasutatud vaid 50 simulatsiooni (R = 50). Päris analüüsis peaks see number olema palju suurem, nt R= 2000.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1632</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data =</span> atp, <span class="at">statistic =</span> mybs, <span class="at">R =</span> <span class="dv">50</span>, <span class="at">stype =</span> <span class="st">"i"</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>results</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = atp, statistic = mybs, R = 50, stype = "i")


Bootstrap Statistics :
     original      bias    std. error
t1* 0.1063243 0.004948775  0.02477052
t2* 0.0926108 0.005312717  0.02398158</code></pre>
</div>
</div>
<p>Simulatsioon näitab meile algset ATE ja ATT väärtust (<em>original</em>), seda kui palju simuleeritud keskmised erinevad algsest väärtusest (<em>bias</em>) ja simuleeritud parameetrite väärtuste standardviga (<em>std. error</em>).</p>
<p>Simuleeritud väärtuste järgi saame konstrueerida usaldusintervallid erinevate eelduste korral. Näiteks ATE jaoks (mis oli esimene simuleeritud parameeter):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boot.ci</span>(</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  results,</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">index =</span> <span class="dv">1</span>, <span class="co">#sest esimene parameeter funktsiooni väljundis</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"norm"</span>, <span class="st">"basic"</span>, <span class="st">"perc"</span>, <span class="st">"bca"</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in norm.inter(t, adj.alpha): extreme order statistics used as endpoints</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
Based on 50 bootstrap replicates

CALL : 
boot.ci(boot.out = results, type = c("norm", "basic", "perc", 
    "bca"), index = 1)

Intervals : 
Level      Normal              Basic         
95%   ( 0.0528,  0.1499 )   ( 0.0510,  0.1590 )  

Level     Percentile            BCa          
95%   ( 0.0536,  0.1617 )   ( 0.0503,  0.1415 )  
Calculations and Intervals on Original Scale
Some basic intervals may be unstable
Some percentile intervals may be unstable
Warning : BCa Intervals used Extreme Quantiles
Some BCa intervals may be unstable</code></pre>
</div>
</div>
<p>Ja ATT jaoks</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boot.ci</span>(</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  results,</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">index =</span> <span class="dv">2</span>, <span class="co">#sest teine parameeter funktsiooni väljundis</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"norm"</span>, <span class="st">"basic"</span>, <span class="st">"perc"</span>, <span class="st">"bca"</span>)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in norm.inter(t, adj.alpha): extreme order statistics used as endpoints</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
Based on 50 bootstrap replicates

CALL : 
boot.ci(boot.out = results, type = c("norm", "basic", "perc", 
    "bca"), index = 2)

Intervals : 
Level      Normal              Basic         
95%   ( 0.0403,  0.1343 )   ( 0.0370,  0.1518 )  

Level     Percentile            BCa          
95%   ( 0.0334,  0.1482 )   ( 0.0273,  0.1285 )  
Calculations and Intervals on Original Scale
Some basic intervals may be unstable
Some percentile intervals may be unstable
Warning : BCa Intervals used Extreme Quantiles
Some BCa intervals may be unstable</code></pre>
</div>
</div>
<p>Tulemuseks on erinevad usaldusvahemikud:</p>
<ul>
<li><p>Normal - kasutab normaaljaotuse eeldust ja leiab usalduspiirid kui pluss-miinus 1.96 korda simuleeritud standardviga. See on lihtne, aga eeldab, et jaotus on sümmeetriline.</p></li>
<li><p>Percentile - leiab simuleeritud andmetest 95%lise usalduspiiri võttes mõlemast jaotuse otsast 2.5% vaatlusi maha. See sobib hästi, kui jaotus on ebasümmeetriline.</p></li>
<li><p>Basic - võtab esialgse “percentile” usalduspiirid ja paneb selle esialgse punkthinnangu ümber.</p></li>
<li><p>BCa - “bias corrected” ja “accelerated” - parandab “percentile” usalduspiire. Võiks pidada parimaks lähenemiseks. Nihutab protsentiile.</p></li>
</ul>
<p>Taolist lähenemist saame kasutada palju keerulisemate mudelite puhul.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopeeritud!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopeeritud!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02-pomate.html" class="pagination-link" aria-label="Potentsiaalse tulemuse mudel">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Potentsiaalse tulemuse mudel</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-difdif.html" class="pagination-link" aria-label="Juurdekasvude erinevus (DIF-DIF)">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Juurdekasvude erinevus (DIF-DIF)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>