<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="et" xml:lang="et"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Juurdekasvude erinevus (DIF-DIF) – Põhjuslike seoste hindamine majanduses</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-rdd.html" rel="next">
<link href="./03-regressioon.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Tulemusi pole",
    "search-matching-documents-text": "sobivat dokumenti",
    "search-copy-link-title": "Kopeeri link otsingule",
    "search-hide-matches-text": "Peida lisavastavused",
    "search-more-match-text": "veel üks vastavus selles dokumendis",
    "search-more-matches-text": "rohkem vastavusi selles dokumendis",
    "search-clear-button-title": "Puhasta",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Tühista",
    "search-submit-button-title": "Esita",
    "search-label": "Otsi"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Lülita külgriba navigeerimist" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-difdif.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Juurdekasvude erinevus (DIF-DIF)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Lülita külgriba navigeerimist" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Otsi" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Põhjuslike seoste hindamine majanduses</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Otsi"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eessõna</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-sissejuhatus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Sissejuhatus</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pohimoistedkordamiseks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Põhimõisted eksamiks kordamiseks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-dag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Suunatud atsüklilised graafid (DAG)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-pom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Potentsiaalse tulemuse mudel</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-regressioon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regressioonimudeli kasutamine</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-difdif.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Juurdekasvude erinevus (DIF-DIF)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-rdd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regressiooni katkemise meetod</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-sobitamine.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sobitamine</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-ivmeetod.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Instrumentmuutuja</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-synthcontr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Sünteetilise võrdlusobjekti meetod</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-mlpuumets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Masinõppemudelid</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-mllasso.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">LASSO mõju hindamisel</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-tehajaideed.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Teha</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sisukord</h2>
   
  <ul>
  <li><a href="#mudeli-seade" id="toc-mudeli-seade" class="nav-link active" data-scroll-target="#mudeli-seade"><span class="header-section-number">6.1</span> Mudeli seade</a>
  <ul class="collapse">
  <li><a href="#klassikaline-2x2-did-disain" id="toc-klassikaline-2x2-did-disain" class="nav-link" data-scroll-target="#klassikaline-2x2-did-disain">Klassikaline 2x2 DiD disain</a></li>
  <li><a href="#did-hinnang-valemina" id="toc-did-hinnang-valemina" class="nav-link" data-scroll-target="#did-hinnang-valemina">DiD hinnang valemina</a></li>
  <li><a href="#did-regressioonimudelina" id="toc-did-regressioonimudelina" class="nav-link" data-scroll-target="#did-regressioonimudelina">DiD regressioonimudelina</a></li>
  <li><a href="#paralleelse-trendi-eeldus-ja-att" id="toc-paralleelse-trendi-eeldus-ja-att" class="nav-link" data-scroll-target="#paralleelse-trendi-eeldus-ja-att">Paralleelse trendi eeldus ja ATT</a></li>
  <li><a href="#kahesuunaline-fikseeritud-efektide-mudel-twfe" id="toc-kahesuunaline-fikseeritud-efektide-mudel-twfe" class="nav-link" data-scroll-target="#kahesuunaline-fikseeritud-efektide-mudel-twfe">Kahesuunaline fikseeritud efektide mudel (TWFE)</a></li>
  <li><a href="#sündmusuuring-event-study" id="toc-sündmusuuring-event-study" class="nav-link" data-scroll-target="#sündmusuuring-event-study">Sündmusuuring (Event study)</a></li>
  <li><a href="#paralleelse-trendi-eelduse-test" id="toc-paralleelse-trendi-eelduse-test" class="nav-link" data-scroll-target="#paralleelse-trendi-eelduse-test">Paralleelse trendi eelduse test</a></li>
  <li><a href="#edasiarendused" id="toc-edasiarendused" class="nav-link" data-scroll-target="#edasiarendused">Edasiarendused</a></li>
  </ul></li>
  <li><a href="#näide-pensionipoliitika-mõju-kohta-hõivemäärale" id="toc-näide-pensionipoliitika-mõju-kohta-hõivemäärale" class="nav-link" data-scroll-target="#näide-pensionipoliitika-mõju-kohta-hõivemäärale"><span class="header-section-number">6.2</span> Näide pensionipoliitika mõju kohta hõivemäärale</a></li>
  <li><a href="#näide-tööturukoolituse-mõju-kohta" id="toc-näide-tööturukoolituse-mõju-kohta" class="nav-link" data-scroll-target="#näide-tööturukoolituse-mõju-kohta"><span class="header-section-number">6.3</span> Näide tööturukoolituse mõju kohta</a>
  <ul class="collapse">
  <li><a href="#kirjeldav-statistiline-analüüs" id="toc-kirjeldav-statistiline-analüüs" class="nav-link" data-scroll-target="#kirjeldav-statistiline-analüüs">Kirjeldav statistiline analüüs</a></li>
  <li><a href="#käsitsi-did" id="toc-käsitsi-did" class="nav-link" data-scroll-target="#käsitsi-did">Käsitsi DiD</a></li>
  <li><a href="#joonis" id="toc-joonis" class="nav-link" data-scroll-target="#joonis">Joonis</a></li>
  <li><a href="#regressioonanalüüsiga-did" id="toc-regressioonanalüüsiga-did" class="nav-link" data-scroll-target="#regressioonanalüüsiga-did">Regressioonanalüüsiga DiD</a></li>
  <li><a href="#paneelandmete-mudel-twfe" id="toc-paneelandmete-mudel-twfe" class="nav-link" data-scroll-target="#paneelandmete-mudel-twfe">Paneelandmete mudel TWFE</a></li>
  <li><a href="#sündmusuuring" id="toc-sündmusuuring" class="nav-link" data-scroll-target="#sündmusuuring">Sündmusuuring</a></li>
  <li><a href="#keerulisemad-ja-paindlikumad-mudelid---vabatahtlik" id="toc-keerulisemad-ja-paindlikumad-mudelid---vabatahtlik" class="nav-link" data-scroll-target="#keerulisemad-ja-paindlikumad-mudelid---vabatahtlik">Keerulisemad ja paindlikumad mudelid - vabatahtlik</a></li>
  </ul></li>
  <li><a href="#mõju-kalendriaja-järgi" id="toc-mõju-kalendriaja-järgi" class="nav-link" data-scroll-target="#mõju-kalendriaja-järgi"><span class="header-section-number">6.4</span> Mõju kalendriaja järgi</a>
  <ul class="collapse">
  <li><a href="#viited" id="toc-viited" class="nav-link" data-scroll-target="#viited">Viited:</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Juurdekasvude erinevus (DIF-DIF)</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    <div>
    <div class="quarto-title-meta-heading">Muudetud</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">23/09/2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="mudeli-seade" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="mudeli-seade"><span class="header-section-number">6.1</span> Mudeli seade</h2>
<p>Juurdekasvude erinevuse meetod või erinevuste vahe meetod (<em>Differences-in-Differences</em>, DIF-DIF, DiD) on üks populaarsemaid kvaasi-eksperimentaalseid meetodeid põhjusliku mõju hindamiseks majanduses. See eemaldab ajas muutumatud erinevused osalus- ja võrldusgrupi vahel ja või ka ajas muutuvad tegurid, mis mõjutavad mõlemaid gruppe ühtemoodi.</p>
<section id="klassikaline-2x2-did-disain" class="level3">
<h3 class="anchored" data-anchor-id="klassikaline-2x2-did-disain">Klassikaline 2x2 DiD disain</h3>
<p>Kõige lihtsamal kujul on meil kaks rühma ja kaks ajahetke:</p>
<ul>
<li>Rühmad(<span class="math inline">\(D\)</span>):
<ul>
<li><span class="math inline">\(D=1\)</span>: Osalusrühm (<em>Treatment</em>), kes saab mingil hetkel sekkumise, nt osaleb tööturukoolituses, osaleb reklaamikampaanias jm.</li>
<li><span class="math inline">\(D=0\)</span>: Võrdlusrühm (<em>Control</em>), kes sekkumist ei saa.</li>
</ul></li>
<li>Aeg (<span class="math inline">\(t\)</span>):
<ul>
<li><span class="math inline">\(t=1\)</span>: Ajahetk pärast sekkumist (<em>Post</em>).</li>
<li><span class="math inline">\(t=0\)</span>: Ajahetk enne sekkumist (<em>Pre</em>).</li>
</ul></li>
</ul>
</section>
<section id="did-hinnang-valemina" class="level3">
<h3 class="anchored" data-anchor-id="did-hinnang-valemina">DiD hinnang valemina</h3>
<p>DiD hinnang (<span class="math inline">\(\hat{\delta}_{DiD}\)</span>) leitakse kui erinevus osalejate ajas toimunud muutuse ja võrdlusrühma ajas toimunud muutuse vahel:</p>
<p><span class="math display">\[
\hat{\delta}_{DiD} = \underbrace{(\bar{Y}_{t=1}^{D=1} - \bar{Y}_{t=0}^{D=1})}_{\text{Muutus osalejatel}} - \underbrace{(\bar{Y}_{t=1}^{D=0} - \bar{Y}_{t=0}^{D=0})}_{\text{Muutus võrdlusrühmal}}
\]</span> Kus <span class="math inline">\(\bar{Y}_{T}^{D}\)</span> on tulemuse keskmine vastavas grupis ja ajahetkel.</p>
<p>Kui me vaatame ainult erinevust osalejate grupi piires, siis seda nimetatakse ka enne-pärast hinnanguks (<em>before-after estimator</em>). Pikema aegrea puhul, kus jälgime vaatlusi enne ja pärast meedet, on tegemist aegrea katkemise meetodiga (<em>interrupted time series analysis</em>).</p>
<p><span class="math display">\[ \hat{\delta}_{BA} = (\bar{Y}_{t=1}^{D=1} - \bar{Y}_{t=0}^{D=1}) \]</span></p>
<p>Sellisel juhul kasutame osalejate mineviku väärtuseid võrdlusseisundina. Seega eeldame, et potentsiaalne tulemus peale meedet, kui meedet ei oleks tegelikult toimunud, on võrdne potentsiaalse tulemusega enne meedet.</p>
<p><span class="math display">\[ E({Y}_{t=1}^{0}|D=1) = E({Y}_{t=0}^{0}|D=1) \]</span></p>
<p>See eeldab potentsiaalsete tulemuste püsivust ajas ja kõik on seotud sekkumisega. See on võimalik lühikeste programmide korral. Näiteks küsime inimeste teadmisi toote kohta enne ja pärast toote reklaami.</p>
</section>
<section id="did-regressioonimudelina" class="level3">
<h3 class="anchored" data-anchor-id="did-regressioonimudelina">DiD regressioonimudelina</h3>
<p>DiD hinnangut saab leida ka lineaarse regressioonimudeli abil, kasutades interaktsiooniliiget:</p>
<p><span class="math display">\[Y_{it} = \alpha + \beta_1 \text{D}_i + \beta_2 \text{Post}_t + \delta*(\text{D}_i \times \text{Post}_t) + \epsilon_{it}
\]</span></p>
<p>Kus:</p>
<ul>
<li><span class="math inline">\(\alpha\)</span>: Kontrollgrupi keskmine enne sekkumist (<em>Constant</em>).</li>
<li><span class="math inline">\(\beta_1\)</span>: Gruppidevaheline püsiv erinevus (<em>Treatment Group Effect</em>).</li>
<li><span class="math inline">\(\beta_2\)</span>: Ajaline trend, mis on ühine mõlemale grupile (<em>Time Trend</em>).</li>
<li>** <span class="math inline">\(\delta_{DiD}\)</span> **: Põhjuslik mõju ehk huvipakkuv parameeter (ATT). See näitab lisandumist tulemuses, mis tekib ainult osalejatel pärast sekkumist.</li>
</ul>
<p>Pangem tähele, et DiD meetod leiab mõju osalejate jaoks (ATT - <em>Average Treatment Effect on the Treated</em>).</p>
</section>
<section id="paralleelse-trendi-eeldus-ja-att" class="level3">
<h3 class="anchored" data-anchor-id="paralleelse-trendi-eeldus-ja-att">Paralleelse trendi eeldus ja ATT</h3>
<p>DiD meetodi kehtivus sõltub <strong>paralleelse trendi eeldusest</strong> (<em>Parallel trends assumption</em>). Eeldus väidab, et sekkumise puudumisel oleks osalusrühma keskmine tulemus muutunud ajas samamoodi nagu võrdlusrühmal.</p>
<p>Matemaatiliselt (kasutades potentsiaalseid tulemusi <span class="math inline">\(Y^0\)</span>):</p>
<p><span class="math display">\[
E[Y^0_{t=1} - Y^0_{t=0} | D=1] = E[Y^0_{t=1} - Y^0_{t=0} | D=0]
\]</span></p>
<p>Kuidas see eeldus tagab, et DiD arvutus annab meile ATT hinnangu? Vaatame seda korra matemaatiliselt.</p>
<p>Meie tegelik eesmärk on leida keskmine mõju osalejatele (ATT) ehk mis oleks meetme mõju (st potentsiaalsete tulemuste erinevus) peale meetme toimumist (ajahetkel <span class="math inline">\(t = 1\)</span>):</p>
<p><span class="math display">\[ATT = E[Y^1_{t=1} - Y^0_{t=1} | D=1] \]</span> Kuna <span class="math inline">\(Y^0_{t=1}\)</span> (osalejate tulemus ilma sekkumiseta) ei ole vaadeldav, siis kasutame paralleelse trendi eeldust selle asendamiseks. Teeme selle läbi samm-haaval. Vaata selgitusi peale valemit.</p>
<p><span class="math display">\[\begin{aligned}ATT &amp; = E[Y^1_{t=1} - Y^0_{t=1} | D=1] \\
\text(1) &amp; = E[Y^1_{t=1}|D=1] -E[Y^0_{t=1} | D=1]  \\
\text(2) &amp; = E[Y^1_{t=1}|D=1] -E[Y^0_{t=1} | D=1] + \underbrace{E[Y^0_{t=0} | D=1] - E[Y^0_{t=0} | D=1]}_{\text{Liidame ja lahutame}} \\
\text(3) &amp; = \underbrace{E[Y^1_{t=1}|D=1] - E[Y^0_{t=0} | D=1]}_{\text{Tegelik muutus}} - \underbrace{(E[Y^0_{t=1} | D=1] - E[Y^0_{t=0} | D=1])}_{\text{Muutus ilma meetmeta}} \\
\text(4) &amp; = E[Y^1_{t=1}|D=1] - E[Y^0_{t=0} | D=1] - \underbrace{(E[Y^0_{t=1} | D=0] - E[Y^0_{t=0} | D=0])}_{\text{Paralleelse trendi eeldus}} \\
\text(5) &amp; = E[Y_{t=1}|D=1] - E[Y_{t=0} | D=1] - (E[Y_{t=1} | D=0] - E[Y_{t=0} | D=0])
\end{aligned}
\]</span></p>
<p>Rida (1) on see, mis meid tegelikult huvitab ja kirjutame selle lihtsalt pikemalt lahti. Real (2) liidame ja lahutame potentsiaalse tulemuse enne meedet osalusrühma seas. Sisuliselt liidame nulli. Real (3) muudame lihtsat liidetavate järjekorda. Esimene liige on nüüd tegelik muutus osalejatel: <span class="math inline">\(E[Y^1_{t=1} | D=1] - E[Y^0_{t=0} | D=1]\)</span> ja teine liige on muutus osalejatel, kui sekkumist poleks olnud. Nüüd toome sisse paralleelse trendi eelduse. Eelduse kohaselt on muutus osalejate seas võrdne muutusega võrdlusrühma seas (rida (4) teine pool). Viimaks asendame potentsiaalsed tulemused tegelike väärtustega ja saamegi meie DiD hinnangu.</p>
<p>Seega, kui on täidetud paralleelse trendi eeldus, siis annab taoline arvutus meile mõju osalejate jaoks:</p>
<p><span class="math display">\[
ATT = (\text{Osalusrühma muutus}) - (\text{Võrdlusrühma muutus})
\]</span></p>
</section>
<section id="kahesuunaline-fikseeritud-efektide-mudel-twfe" class="level3">
<h3 class="anchored" data-anchor-id="kahesuunaline-fikseeritud-efektide-mudel-twfe">Kahesuunaline fikseeritud efektide mudel (TWFE)</h3>
<p>Kui andmed on paneelkujul, st me jälgime palju objekte eri ajahetkedel, kasutatakse lineaarset paneelandmete fikseeritud efektidega mudelit - TWFE mudel (<em>Two-way Fixed Effects model</em>). See on ka 2x2 DiD disaini üldistus, mis lubab, et meil toimuda meetmes osalemine erinevatel ajahetkedel. Näiteks mõned ettevõtted saavad toetust ühel aastal, järgmised teisel aastal jne. Sellisel juhul <span class="math inline">\(D\)</span> väärtus objekti jaoks sõltub ajahetkest ja tähistame seda <span class="math inline">\(D_{it}\)</span>.</p>
<p><span class="math display">\[
Y_{it} = \alpha_i + \gamma_t + \delta D_{it} + \mathbf{X}_{it}\beta + \epsilon_{it}
\]</span></p>
<p>Kus:</p>
<ul>
<li><span class="math inline">\(Y_{it}\)</span>: Tulemusmuutuja objektile <span class="math inline">\(i\)</span> ajahetkel <span class="math inline">\(t\)</span>.</li>
<li><span class="math inline">\(\alpha_i\)</span> (<em>Unit Fixed Effects</em>): objektispetsiifiline fikseeritud efekt. See kontrollib kõiki tegureid, mis on objektile <span class="math inline">\(i\)</span> omased ja ajas ei muutu (nt asukoht, kultuur, geneetika). Asendab ülal olnud <span class="math inline">\(\text{D}_i\)</span> muutujat.</li>
<li><span class="math inline">\(\gamma_t\)</span> (<em>Time Fixed Effects</em>): ajaspetsiifiline fikseeritud efekt. See kontrollib šokke, mis mõjutavad kõiki objekte antud aastal <span class="math inline">\(t\)</span> ühtemoodi (nt majanduskriis, seadusemuudatused). Asendab ülal <span class="math inline">\(\text{Post}_t\)</span> muutujat.</li>
<li><span class="math inline">\(D_{it}\)</span> (Treatment Indicator): Binaarne muutuja, mis on 1, kui objekt <span class="math inline">\(i\)</span> on ajal <span class="math inline">\(t\)</span> sekkumise all. Näiteks kui ettevõtte sai toetust 2020. aastal, siis selle ettevõtte jaoks on see muutuja null enne 2020. aastat ja üks 2020. aastal ja edasi.</li>
<li><span class="math inline">\(\delta\)</span>: ATT hinnang (eeldusel, et mõju on ajas homogeenne).</li>
<li><span class="math inline">\(\mathbf{X}_{it}\)</span>: Muud ajas muutuvad ja objektide vahel erinevad selgitavad tunnused.</li>
</ul>
<p>See mudel eeldab, et mõju avaldub meetme aastal ja on pärast seda püsiv. Kui mõju tegelikult ajas muutub (näiteks alguses on väike, pärast kasvab), siis ülaltoodud mudel seda ei võimalda leida. Selleks, et näidata ajas toimuvat muutust, kasutatakse dünaamilist mudelit.</p>
</section>
<section id="sündmusuuring-event-study" class="level3">
<h3 class="anchored" data-anchor-id="sündmusuuring-event-study">Sündmusuuring (Event study)</h3>
<p>Sündmusuuring (<em>Event Study</em>) on dünaamiline regressioonimudel, mis võimaldab hinnata meetme mõju muutumist ajas ning testida nii visuaalselt ja ka statistiliselt paralleelse trendi eeldust.</p>
<p><strong>Regressioonivalem</strong></p>
<p>Üldkuju:</p>
<p><span class="math display">\[
Y_{it} = \alpha_i + \gamma_t + \sum_{k=-K, k \neq -1}^{L} \beta_k \cdot D_{it}^k + \mathbf{X}_{it}\beta + \epsilon_{it}
\]</span></p>
<p>Lisandunud muutujate selgitus:</p>
<ul>
<li><span class="math inline">\(k\)</span>: Suhteline aeg sündmuseni (<span class="math inline">\(t - E_i\)</span>, kus <span class="math inline">\(E_i\)</span> on sündmuse toimumise aeg objekti <span class="math inline">\(i\)</span> jaoks).
<ul>
<li><span class="math inline">\(k &lt; 0\)</span>: Perioodid enne meedet (<em>Leads</em>).</li>
<li><span class="math inline">\(k \ge 0\)</span>: Perioodid pärast meedet (<em>Lags</em>).</li>
<li>Periood <span class="math inline">\(k = -1\)</span> on välja jäetud ja kasutame seda referentspunktina</li>
<li><span class="math inline">\(K\)</span> ja <span class="math inline">\(L\)</span> sõltuvad andmestiku pikkusest, nt vaatame 5 aastat enne ja 5 pärast pärast meedet.</li>
</ul></li>
<li><span class="math inline">\(D_{it}^k\)</span>: Sündmuse indikaatorid (<em>Event Time Dummies</em>).
<ul>
<li>Muutuja on 1, kui objekt <span class="math inline">\(i\)</span> on ajahetkel <span class="math inline">\(t\)</span> täpselt <span class="math inline">\(k\)</span> perioodi kaugusel sündmusest.</li>
<li>Muutuja on 0 muudel juhtudel.</li>
</ul></li>
<li><span class="math inline">\(\beta_k\)</span>: Huvipakkuvad koefitsiendid:
<ul>
<li>Kui <span class="math inline">\(k &lt; 0\)</span> (Meetme-eelne periood): <span class="math inline">\(\beta_k\)</span> näitab erinevust osalus- ja võrdlusrühma vahel enne meedet. See testib paralleelse trendi eeldus. Kui eeldus kehtib, peaksid need <span class="math inline">\(\beta\)</span>-d olema statistiliselt nullist eristamatud (nulljoone lähedal).</li>
<li>Kui <span class="math inline">\(k \ge 0\)</span> (Meetmejärgne periood): <span class="math inline">\(\beta_k\)</span> näitab meetme dünaamilist mõju <span class="math inline">\(k\)</span> perioodi pärast sündmust.</li>
</ul></li>
<li><span class="math inline">\(k \neq -1\)</span>: Väljajäetud kategooria.
<ul>
<li>Tavaliselt jäetakse mudelist välja periood vahetult enne sündmust (<span class="math inline">\(k = -1\)</span>), et vältida multikollineaarsust. Kõiki teisi koefitsiente (<span class="math inline">\(\beta_k\)</span>) tõlgendatakse selle baasperioodi suhtes. Eeldame, et perioodil 0 tekib esimest korda avatus meetmele. See pisut sõltub, et kas eeldame, et mõju avaldub juba samal perioodil või alates järgmisest perioodist.</li>
</ul></li>
</ul>
</section>
<section id="paralleelse-trendi-eelduse-test" class="level3">
<h3 class="anchored" data-anchor-id="paralleelse-trendi-eelduse-test">Paralleelse trendi eelduse test</h3>
<p>Sündmusuuringu spetsifikatsiooni korral saame testida, kas enne meedet paralleelne trend kehtis. See lisab kindlust eeldusel, et paralleelne trend oleks jätkunud ka ilma meetmeta. Seda kontrollime hüpoteesiga, kas kõik kordajad enne meedet on korraga nullid:</p>
<p><span class="math display">\[
H_0: \beta_{-K} = \beta_{-K+1} = \cdots = \beta_{-2} = 0.
\]</span></p>
<p>alternatiivne hüpotees oleks</p>
<p><span class="math display">\[
H_1: \text{vähemalt üks  } \beta_k \neq 0, \qquad k &lt; -1.
\]</span></p>
<p>Kasutatakse kas Wald testi või F testi. Kui me ei saa <span class="math inline">\(H_0\)</span> ümber lükata, siis see on kooskõlas paralleelse trendi eeldusega. See küll tõesta, et paralleelse trendi eeldus kehtib.</p>
</section>
<section id="edasiarendused" class="level3">
<h3 class="anchored" data-anchor-id="edasiarendused">Edasiarendused</h3>
<p>DiD meetodit võib kombineerida sobitamisega (vt järgmist peatükki). Sellisel juhul tehakse võrdlusrühm eelnevalt sarnaseks osalusrühmaga kasutades meetmele eelnevaid tunnuste väärtusi ja meetmest sõltumatuid tunnuseid. Näiteks inimese sugu, vanus ja palk enne meedet.</p>
<p>DiD meetodil on tänapäeval palju edasiarendusi. Kui meetme mõjus ajas muutub (nt kasvab või kahaneb) ja meetmes osalevad ettevõtted või inimesed eri ajahetkedel (nn <em>staggered design</em>), siis on oht saada tavalise TWFE mudeliga nihkega hinnanguid.</p>
<p><em>(TODO! Lisada viited olulisematele allikatele)</em> Sun &amp; Abraham (2021, Journal of Econometrics) Callaway &amp; Sant’Anna (2021, Journal of Econometrics) Roth (2022, American Economic Review: Insights).</p>
</section>
</section>
<section id="näide-pensionipoliitika-mõju-kohta-hõivemäärale" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="näide-pensionipoliitika-mõju-kohta-hõivemäärale"><span class="header-section-number">6.2</span> Näide pensionipoliitika mõju kohta hõivemäärale</h2>
<p>Aastatel 1995–2002 tõusus Eestis pensioniiga meestel 61-lt 63-le eluaastale. (Tegelikult lisaks toimus muutus, et pensionärid võisid samal ajal saada pensioni ja töötada.)</p>
<p>Mis oli nende muutuste mõju 60–64-aastaste meeste hõivemäärale? Kuidas eristada pensionipoliitika muutusi majanduskeskkonna muutusest?</p>
<p>Eeldame, et vanusrühm 60–64 on osalusrühm ja vanusrühm 55–59 on võrdlusrühm, keda pensioniea tõus ei mõjutanud, kuid kelle olukord tööturul on sarnane.</p>
<p><strong>Lähteandmed hõivemäära kohta</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Aasta</th>
<th style="text-align: right;">60–64</th>
<th style="text-align: right;">55–59</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1995</td>
<td style="text-align: right;">35.8</td>
<td style="text-align: right;">71.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">2002</td>
<td style="text-align: right;">51.1</td>
<td style="text-align: right;">66.1</td>
</tr>
</tbody>
</table>
<p>Hõivemäärad on protsentides.</p>
<p>Me näeme, et hõivemäär kasvas vanusrühmas 60-64 15.3 protsendipunkti.</p>
<p><span class="math display">\[
51.1 - 35.8 = 15.3
\]</span></p>
<p>Seega enne-pärast hinnang ütleks, et pensioniea tõus tõi kaasa hõivemäära kasvu 15.3 pp.</p>
<p>Aga samal ajal toimusid muud muutused majanduses. Eeldame, et seda võtab kinni sarnane vanusrühm, keda aga pensioniea tõus otseselt ei mõjutanud, sest pensioniiga oli kõrgem. Näeme, et 55–59-aastaste hõivemäär hoopis vähenes 5.7 protsendipunkti.</p>
<p><span class="math display">\[
66.1 - 71.8 = -5.7
\]</span></p>
<p>Seega DiD hinnang, mis võrdleb osalusrühma hõivemäära muutust võrdlusrühma hõivemäära muutusega, on:</p>
<p><span class="math display">\[
\text{DiD}
= (51.1 - 35.8) - (66.1 - 71.8) = 15.3 - (-5.7) = 21.0
\]</span></p>
<p>Seega pensioniea tõus suurendas 60–64-aastaste meeste hõivemäära 21 protsendipunkti. Tegelikes andmetes me näeme seda mõju väiksemana, 15.3 protsendipunkti, sest majanduses läks olukord kehvemaks ja seetõttu hõivemäär vähenes 5.7 protsendipunkti.</p>
<p>Selle hinnangu põhjusliku mõjuna tõlgendamiseks peab kehtima eeldus, et ilma pensioniea tõusuta oleks 60–64- ja 55–59-aastaste hõivemäär muutunud ajas sarnaselt. Tegelikkuses tuleb arvestada, et vanusrühmad võivad erineda muude näitajate poolest (nt haridus, rahvus), mille mõju hõivemäärale võib olla erinev sõltuvalt majanduse olukorrast. Lisaks võivad esineda ka vanusrühmade omavahelised seosed, sest nad konkureerivad omavahel tööturul. (Ei kehti SUTVA eeldus.)</p>
</section>
<section id="näide-tööturukoolituse-mõju-kohta" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="näide-tööturukoolituse-mõju-kohta"><span class="header-section-number">6.3</span> Näide tööturukoolituse mõju kohta</h2>
<p>Kasutame näitena anonümiseeritud andmeid Poliitikauuringute Keskuse Praxis raportist Leetmaa, Võrk, Kupts, Kirss (2015) „Programmi Täiskasvanute tööalane koolitus ja arendustegevused võrdlusrühmapõhine mõju hindamine“ <a href="https://www.praxis.ee/tood/programmi-taiskasvanute-tooalane-koolitus-ja-arendustegevused-moju-hindamine/" class="uri">https://www.praxis.ee/tood/programmi-taiskasvanute-tooalane-koolitus-ja-arendustegevused-moju-hindamine/</a></p>
<p>Andmestik on pisut hägustatud, mistõttu päris samu punkthinnanguid ei saa, mis algses uuringus.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(coefplot)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(panelView)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(did)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Andmestiku kirjeldus</p>
<table class="caption-top table">
<colgroup>
<col style="width: 45%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th>Tunnus</th>
<th>Selgitus</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>id</code></td>
<td>Inimese pseudo-ID</td>
</tr>
<tr class="even">
<td><code>koolituses</code></td>
<td>Inimene osales koolituses 2010. või 2011. aastal</td>
</tr>
<tr class="odd">
<td><code>koolitusaasta</code></td>
<td>Koolituse aasta: 2010 või 2011; kui inimene koolitusel ei osalenud, siis 0</td>
</tr>
<tr class="even">
<td><code>palk2008</code>, <code>palk2009</code>, …, <code>palk2013</code></td>
<td>Inimese aasta töötasu (brutosumma) aastatel 2008–2013, tuhandetes eurodes</td>
</tr>
<tr class="odd">
<td><code>haridus</code></td>
<td>Haridustase: 2 – põhiharidus; 3 – üldkeskharidus; 4 – kutseharidus põhihariduse baasil; 5 – kutseharidus keskhariduse baasil; 6 – kõrgharidus</td>
</tr>
<tr class="even">
<td><code>mees</code></td>
<td>1 – mees; 0 – naine</td>
</tr>
<tr class="odd">
<td><code>eestlane</code></td>
<td>1 – eestlane; 0 – mitte-eestlane</td>
</tr>
<tr class="even">
<td><code>vanus</code></td>
<td>Vanus 2010. aastal</td>
</tr>
<tr class="odd">
<td><code>vanusgr</code></td>
<td>Vanuserühm</td>
</tr>
<tr class="even">
<td><code>seisund</code></td>
<td>Seisund koolitusse minemisel: 1 – töötav; 2 – mitteaktiivne; 3 – töötu</td>
</tr>
<tr class="odd">
<td><code>kulu</code></td>
<td>Koolituse kulu eurodes osaleja kohta</td>
</tr>
</tbody>
</table>
<p>Lugege andmed sisse ja vaadake, et saate aru andmete sisust. Üks fail on laial kujul ja teine on pikal kujul.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Muutke ära andmete kataloog vajadusel</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>datapath <span class="ot">=</span> <span class="st">"http://kodu.ut.ee/~avork/files/oppetoo/pohjustagajarg/"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Lugege sisse andmefailid laial kujul ja pikal kujul</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="fu">paste0</span>(datapath, <span class="st">"adulttraining.csv"</span>))</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>dfl <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="fu">paste0</span>(datapath, <span class="st">"adulttraininglong.csv"</span>))</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="kirjeldav-statistiline-analüüs" class="level3">
<h3 class="anchored" data-anchor-id="kirjeldav-statistiline-analüüs">Kirjeldav statistiline analüüs</h3>
<p>stargazer käsk esitab mugavalt peamised näitajad. Saame vaadata kogu valimit ja eraldi osalus- ja võrdlusrühma.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(df, <span class="at">type =</span> <span class="st">"text"</span>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=========================================================
Statistic       N     Mean    St. Dev.    Min      Max   
---------------------------------------------------------
id            4,586 2,293.500 1,324.008    1      4,586  
koolituses    4,586   0.500     0.500      0        1    
palk2008      4,586   6.063     5.537    0.000   24.959  
palk2009      4,586   4.971     5.003    0.000   22.860  
palk2010      4,586   4.509     4.872    0.000   21.768  
palk2011      4,586   5.014     5.181    0.000   22.508  
palk2012      4,586   5.737     5.764    0.000   25.584  
palk2013      4,586   6.208     6.217    0.000   27.530  
haridus       4,586   4.154     1.287      2        6    
mees          4,586   0.573     0.495      0        1    
eestlane      4,586   0.657     0.475      0        1    
vanus         4,586  39.831    11.892     16       73    
kulu          2,293 3,334.167 1,461.837 331.320 6,624.000
koolitusaasta 4,586 1,005.240 1,005.350    0      2,011  
seisund       4,586   1.463     0.749      1        3    
---------------------------------------------------------</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(koolituses <span class="sc">==</span><span class="dv">1</span>), <span class="at">type =</span> <span class="st">"text"</span>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=========================================================
Statistic       N     Mean    St. Dev.    Min      Max   
---------------------------------------------------------
id            2,293 1,147.000  662.076     1      2,293  
koolituses    2,293   1.000     0.000      1        1    
palk2008      2,293   6.399     5.412    0.000   24.959  
palk2009      2,293   5.298     4.971    0.000   22.860  
palk2010      2,293   4.736     4.817    0.000   21.768  
palk2011      2,293   5.492     5.174    0.000   22.508  
palk2012      2,293   6.339     5.758    0.000   25.584  
palk2013      2,293   6.776     6.293    0.000   27.530  
haridus       2,293   4.215     1.288      2        6    
mees          2,293   0.604     0.489      0        1    
eestlane      2,293   0.652     0.476      0        1    
vanus         2,293  39.310    11.719     17       73    
kulu          2,293 3,334.167 1,461.837 331.320 6,624.000
koolitusaasta 2,293 2,010.481   0.500    2,010    2,011  
seisund       2,293   1.578     0.846      1        3    
---------------------------------------------------------</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(koolituses <span class="sc">==</span><span class="dv">0</span>), <span class="at">type =</span> <span class="st">"text"</span>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===================================================
Statistic       N     Mean    St. Dev.  Min   Max  
---------------------------------------------------
id            2,293 3,440.000 662.076  2,294 4,586 
koolituses    2,293   0.000    0.000     0     0   
palk2008      2,293   5.726    5.640   0.000 24.959
palk2009      2,293   4.644    5.014   0.000 22.860
palk2010      2,293   4.282    4.918   0.000 21.768
palk2011      2,293   4.536    5.146   0.000 22.508
palk2012      2,293   5.135    5.708   0.000 25.584
palk2013      2,293   5.640    6.088   0.000 27.530
haridus       2,293   4.092    1.283     2     6   
mees          2,293   0.543    0.498     0     1   
eestlane      2,293   0.662    0.473     0     1   
vanus         2,293  40.353    12.042   16     64  
koolitusaasta 2,293   0.000    0.000     0     0   
seisund       2,293   1.348    0.616     1     3   
---------------------------------------------------</code></pre>
</div>
</div>
<p>Võite ka võrrelda muidugi lithsa risttabeliga. Näiteks, kas koolituses osalejate seas on rohkem mehi kui mitteosalejate seas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Gruppide võrdlus</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(<span class="st">"Koolituses"</span> <span class="ot">=</span> df<span class="sc">$</span>koolituses, <span class="st">"Mees"</span> <span class="ot">=</span> df<span class="sc">$</span>mees),<span class="dv">1</span>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Mees
Koolituses         0         1
         0 0.4570432 0.5429568
         1 0.3964239 0.6035761</code></pre>
</div>
</div>
</section>
<section id="käsitsi-did" class="level3">
<h3 class="anchored" data-anchor-id="käsitsi-did">Käsitsi DiD</h3>
<p>Mis on palga muutus osalusgrupis ja võrdlusgrupis? Vaatame näiteks aastaid 2008 vs 2013.</p>
<p>Arvutame esmalt keskmised palgad mõlemas rühmas ja seejärel leiame palkade kasvu <em>palgamuut</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(koolituses) <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">palk2008 =</span> <span class="fu">mean</span>(palk2008),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">palk2013 =</span> <span class="fu">mean</span>(palk2013)) <span class="sc">%&gt;%</span> </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">palgamuut =</span> palk2013<span class="sc">-</span>palk2008)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Enne-pärast hinnang</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>temp</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  koolituses palk2008 palk2013 palgamuut
       &lt;int&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1          0     5.73     5.64   -0.0865
2          1     6.40     6.78    0.377 </code></pre>
</div>
</div>
<p>Näeme, et osalejatel kavas palk 0.377 ehk 377 euro võrra. Mitteosalejatel palk hoopis vähemes 0.0865 võrra.</p>
<p>Leiame nüüd DiD hinnangu. Lahutame teisest reast esimese.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>difdif <span class="ot">=</span> temp<span class="sc">$</span>palgamuut[<span class="dv">2</span>] <span class="sc">-</span> temp<span class="sc">$</span>palgamuut[<span class="dv">1</span>]</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>difdif</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.463845</code></pre>
</div>
</div>
<p>DiD hinnang on 0.464 ehk osalusrühma palk kasvas tänu koolitusele 464 euro võrra aastas. Antud juhul, me ei arvesta mitte mingite muude erinevustega osalus- ja võrdlusrühmas.</p>
</section>
<section id="joonis" class="level3">
<h3 class="anchored" data-anchor-id="joonis">Joonis</h3>
<p>Kujutame keskmiste palkade arengut osalus- ja võrdlusrühmas ka joonisel. Selleks esmalt teeme valmis keskmiste andmestiku. Kasutame selleks meie andmestikku pikal kujul.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Keskmised palgad osalus ja võrdlusrühmas</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> dfl <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(koolituses, aasta) <span class="sc">%&gt;%</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">palk =</span> <span class="fu">mean</span>(palk))</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'koolituses'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>temp</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
# Groups:   koolituses [2]
   koolituses aasta  palk
        &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
 1          0  2008  5.73
 2          0  2009  4.64
 3          0  2010  4.28
 4          0  2011  4.54
 5          0  2012  5.14
 6          0  2013  5.64
 7          1  2008  6.40
 8          1  2009  5.30
 9          1  2010  4.74
10          1  2011  5.49
11          1  2012  6.34
12          1  2013  6.78</code></pre>
</div>
</div>
<p>Ja nüüd kuvame selle ka joonisel. Lisame joonisele kasti, kus on toodud koolituse toimumise periood osalusrühmas. Näeme, et koolituses osalejatel olid juba enne koolitust kõrgemad palgad. Samas trend on sarnane enne koolitust, mõlemas rühmas palgad kukuvad 2008-2009.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Praksis tee rida haaval</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(temp, <span class="fu">aes</span>(<span class="at">x =</span> aasta, <span class="at">y =</span> palk, <span class="at">color =</span> <span class="fu">factor</span>(koolituses))) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_rect</span>(<span class="at">xmin =</span> <span class="fl">2009.5</span>, <span class="at">xmax =</span> <span class="fl">2011.5</span>, <span class="at">ymin =</span> <span class="fu">min</span>(temp<span class="sc">$</span>palk)<span class="sc">-</span><span class="fl">0.5</span>, <span class="at">ymax =</span> <span class="fu">max</span>(temp<span class="sc">$</span>palk), <span class="at">fill =</span> <span class="st">"grey100"</span>, </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">alpha =</span> <span class="fl">0.1</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(palk,<span class="dv">1</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">""</span>, <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"tuh.eur"</span>) <span class="sc">+</span> </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-difdif_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="regressioonanalüüsiga-did" class="level3">
<h3 class="anchored" data-anchor-id="regressioonanalüüsiga-did">Regressioonanalüüsiga DiD</h3>
<p>Näitame, et käsitsi tehtud arvutuse 2x2 disaini korral saame teha ka regressioonimudeliga. Selleks jätame alles vaid ülal kasutatud aastad 2008 ja 2013 ja hindame seejärel lineaarse mudeli.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Jätame alles aastad</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>dfls <span class="ot">&lt;-</span> dfl   <span class="sc">%&gt;%</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(aasta <span class="sc">==</span> <span class="dv">2008</span> <span class="sc">|</span> aasta <span class="sc">==</span><span class="dv">2013</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">aasta =</span> <span class="fu">as.factor</span>(aasta))</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>mudel <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> dfls, <span class="at">formula =</span> palk <span class="sc">~</span> koolituses <span class="sc">+</span> aasta <span class="sc">+</span> koolituses<span class="sc">*</span>aasta)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mudel)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = palk ~ koolituses + aasta + koolituses * aasta, 
    data = dfls)

Residuals:
   Min     1Q Median     3Q    Max 
-6.776 -5.279 -1.159  3.224 21.890 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           5.72637    0.12256  46.724  &lt; 2e-16 ***
koolituses            0.67266    0.17332   3.881 0.000105 ***
aasta2013            -0.08647    0.17332  -0.499 0.617872    
koolituses:aasta2013  0.46385    0.24512   1.892 0.058476 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.869 on 9168 degrees of freedom
Multiple R-squared:  0.006445,  Adjusted R-squared:  0.006119 
F-statistic: 19.82 on 3 and 9168 DF,  p-value: 8.386e-13</code></pre>
</div>
</div>
<p>Vabaliige 5.726 näitab keskmist palka võrdlusrühmal enne meedet. Kordaja 0.673 tunnuse <em>koolituses</em> ees näitab, et koolituses osalejatel oli enne meedet palk kõrgem 0.673 võrra ehk nende palk oli 5.726+0.673 = 6.399.</p>
<p>Kordaja -0.086 tunnuse <em>aasta2013</em> ees näitab, et palgad olid võrdlusrühmal peale meedet madalamad ehk 5.726-0.086 = 5.64.</p>
<p>Viimaks ristkorrutis <em>koolituses:aasta2013i</em> näitab, et koolituses osalejatel oli peale meedet palk kõrgem 0.464 võrra. Ehk nende palk oli 5.726+0.673 - 0.086 + 0.464 = 6.777.</p>
<p>Võrdle regressioonimudelist leitud arve ülal toodud 2x2 tabeliga ja veendu, et tulemused on samad. (Ümardamise erinevust arvesse võttes.)</p>
<p>Analoogselt võime valida punktideks enne ja pärast meedet ja teised aastad, näiteks 2009 ja 2012.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Võrrelge nüüd 2009 ja 2012 andmetega</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>dfls <span class="ot">&lt;-</span> dfl <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(aasta <span class="sc">==</span><span class="dv">2009</span> <span class="sc">|</span> aasta <span class="sc">==</span><span class="dv">2012</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">aasta =</span> <span class="fu">as.factor</span>(aasta))</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>mudel <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> dfls, <span class="at">formula =</span> palk <span class="sc">~</span> koolituses <span class="sc">+</span> aasta <span class="sc">+</span> koolituses<span class="sc">*</span>aasta)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mudel)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = palk ~ koolituses + aasta + koolituses * aasta, 
    data = dfls)

Residuals:
   Min     1Q Median     3Q    Max 
-6.339 -4.644 -1.134  2.971 20.449 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            4.6441     0.1123  41.369  &lt; 2e-16 ***
koolituses             0.6534     0.1588   4.116 3.89e-05 ***
aasta2012              0.4910     0.1588   3.092  0.00199 ** 
koolituses:aasta2012   0.5504     0.2245   2.451  0.01425 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.376 on 9168 degrees of freedom
Multiple R-squared:  0.01303,   Adjusted R-squared:  0.01271 
F-statistic: 40.34 on 3 and 9168 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Võrrelge, kuidas muutus hinnang koolituse mõjule? Näete, et see on pisut suurem 0.5504.</p>
<p>Järgnevalt lisame regressioonimudelisse ja muud tegurid, mis võivad mõjutada palka. Pange tähele, et esialgu me ei lisa fikseeritud efekti inimesele. Siis peaksime välja jätma kõik demograafilised tunnused, sest need ei varieeru.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Lisame mudelisse muud tegurid</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Andmestik uuesti</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>difdif1 <span class="ot">&lt;-</span> dfl <span class="sc">%&gt;%</span> </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(aasta <span class="sc">==</span> <span class="dv">2008</span> <span class="sc">|</span> aasta <span class="sc">==</span><span class="dv">2013</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">aasta =</span> <span class="fu">as.factor</span>(aasta)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>         )</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Ja mudel</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>mudel <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> difdif1, <span class="at">formula =</span> palk <span class="sc">~</span> koolituses <span class="sc">+</span> aasta <span class="sc">+</span> </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>              koolituses<span class="sc">*</span>aasta <span class="sc">+</span> mees <span class="sc">+</span> eestlane <span class="sc">+</span> <span class="fu">factor</span>(haridus) <span class="sc">+</span> vanusgr <span class="sc">+</span> <span class="fu">factor</span>(seisund))</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mudel)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = palk ~ koolituses + aasta + koolituses * aasta + 
    mees + eestlane + factor(haridus) + vanusgr + factor(seisund), 
    data = difdif1)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.4026  -3.6984  -0.5935   2.8292  20.9597 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           2.63883    0.26268  10.046  &lt; 2e-16 ***
koolituses            0.49975    0.16041   3.115 0.001842 ** 
aasta2013            -0.08647    0.15749  -0.549 0.582981    
mees                  2.39451    0.11512  20.799  &lt; 2e-16 ***
eestlane              0.30816    0.11864   2.597 0.009408 ** 
factor(haridus)3      0.58185    0.20738   2.806 0.005032 ** 
factor(haridus)4      0.68067    0.19926   3.416 0.000638 ***
factor(haridus)5      1.52820    0.21882   6.984 3.07e-12 ***
factor(haridus)6      2.92520    0.21333  13.712  &lt; 2e-16 ***
vanusgr(25,35]        1.84815    0.18750   9.857  &lt; 2e-16 ***
vanusgr(35,45]        2.25874    0.18872  11.969  &lt; 2e-16 ***
vanusgr(45,55]        1.32949    0.19052   6.978 3.20e-12 ***
vanusgr(55,100]       0.88350    0.22516   3.924 8.78e-05 ***
factor(seisund)2     -4.03936    0.16201 -24.933  &lt; 2e-16 ***
factor(seisund)3     -2.85658    0.16182 -17.652  &lt; 2e-16 ***
koolituses:aasta2013  0.46385    0.22272   2.083 0.037310 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.332 on 9156 degrees of freedom
Multiple R-squared:  0.1808,    Adjusted R-squared:  0.1795 
F-statistic: 134.7 on 15 and 9156 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Esimesena vaatame taas aastaid 2008 ja 2013. Näeme, et koolituse mõju on praktiliselt sama, mis ülal, 0.464.</p>
<p>Võime esitada kordajad ka graafikul käsuga <em>coefplot</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coefplot</span>(mudel)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-difdif_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="paneelandmete-mudel-twfe" class="level3">
<h3 class="anchored" data-anchor-id="paneelandmete-mudel-twfe">Paneelandmete mudel TWFE</h3>
<p>Hindame mudeli ka korrektselt kasutades TWFE lähenemist ja lisame fikseeritud efektid. Selleks kasutame <em>feols</em> käsku <em>fixest</em> paketist. See on mugav, et ei pea käsitsi tegema fiktviiseid (dummy) muutujaid. Need võetakse automaatselt arvesse.</p>
<p>Esmalt peame tegema ka ajas muutuvad koolituse väärtuse tunnuse, mis on võrdne 1-ga peale koolitust. Võrdlusrühmal on see alati null.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>dfl <span class="ot">&lt;-</span> dfl <span class="sc">|&gt;</span>  <span class="fu">mutate</span>(<span class="at">koolitatud =</span> <span class="fu">as.integer</span>(koolituses <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> aasta <span class="sc">&gt;=</span> koolitusaasta))</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Kontrollime joonisel, kas tuli välja nagu soovisime</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">panelview</span>(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  palk <span class="sc">~</span> koolitatud,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dfl,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"id"</span>, <span class="st">"aasta"</span>),</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">pre.post =</span> <span class="cn">TRUE</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">by.timing =</span> <span class="cn">TRUE</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">axis.lab.angle =</span> <span class="dv">90</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>If the number of units is more than 300, we set "gridOff = TRUE".</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>If the number of units is more than 500, we randomly select 500 units to present.
        You can set "display.all = TRUE" to show all units.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-difdif_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Joonis näitab, et tõepoolest on kontrollid ja osalusrühm, kus meede algas erineval ajahetkel.</p>
<p>Hindame nüüd TWFE mudeli. Pangem tähele, et standardvigade arvutamisel lubame isikutel olla erinev vealiikme dispersioon.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>m_twfe <span class="ot">&lt;-</span> <span class="fu">feols</span>(</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  palk <span class="sc">~</span> koolitatud <span class="sc">|</span> id <span class="sc">+</span> aasta,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dfl,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster =</span> <span class="sc">~</span> id</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_twfe)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: palk
Observations: 27,516
Fixed-effects: id: 4,586,  aasta: 6
Standard-errors: Clustered (id) 
           Estimate Std. Error t value Pr(&gt;|t|)    
koolitatud 0.208758   0.093343 2.23645  0.02537 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 2.61339     Adj. R2: 0.727401
                Within R2: 4.309e-4</code></pre>
</div>
</div>
<p>Näeme, et TWFE mudeli järgi on koolituse mõju palkgale 0.209 ühikut ja see on statistiliselt oluline olulisusnivool 0.05.</p>
</section>
<section id="sündmusuuring" class="level3">
<h3 class="anchored" data-anchor-id="sündmusuuring">Sündmusuuring</h3>
<p>Sündmusuuringu kujul mudeli hindamiseks peame lubama koolitusel omada mõju igal aastal enne ja pärast koolitust erinevalt. Selleks teema indikaatormuutujad. Kasutame referentsiks aastat -1. See jääb välja. Seega vaikimisi eeldame, et koolituse mõju algab samal aastal kui koolitus toimus. Nendele, kes koolitust ei saanud, paneme alati väärtuse nullikis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Leiame erinevuse koolituse aastast</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Kõigile koolituses mitteosalejatele paneme selle nulliks</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>dfl <span class="ot">&lt;-</span> dfl <span class="sc">%&gt;%</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">aeg_m3 =</span> <span class="fu">as.integer</span>(koolituses <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> aasta <span class="sc">-</span> koolitusaasta <span class="sc">==</span> <span class="sc">-</span><span class="dv">3</span>),</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">aeg_m2 =</span> <span class="fu">as.integer</span>(koolituses <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> aasta <span class="sc">-</span> koolitusaasta <span class="sc">==</span> <span class="sc">-</span><span class="dv">2</span>),</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># k = -1 jätame välja kui referentsperioodi</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">aeg_0  =</span> <span class="fu">as.integer</span>(koolituses <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> aasta <span class="sc">-</span> koolitusaasta <span class="sc">==</span> <span class="dv">0</span>),</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">aeg_1  =</span> <span class="fu">as.integer</span>(koolituses <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> aasta <span class="sc">-</span> koolitusaasta <span class="sc">==</span> <span class="dv">1</span>),</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">aeg_2  =</span> <span class="fu">as.integer</span>(koolituses <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> aasta <span class="sc">-</span> koolitusaasta <span class="sc">==</span> <span class="dv">2</span>),</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">aeg_3  =</span> <span class="fu">as.integer</span>(koolituses <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> aasta <span class="sc">-</span> koolitusaasta <span class="sc">==</span> <span class="dv">3</span>)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Hindame nüüd TWFE mudeli dünaamiliste efektidega</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>m_twfedyn <span class="ot">&lt;-</span> <span class="fu">feols</span>(</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  palk <span class="sc">~</span> aeg_m3 <span class="sc">+</span> aeg_m2 <span class="sc">+</span> aeg_0 <span class="sc">+</span> aeg_1 <span class="sc">+</span> aeg_2 <span class="sc">+</span> aeg_3 <span class="sc">|</span> id <span class="sc">+</span> aasta,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dfl,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster =</span> <span class="sc">~</span> id</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_twfe)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: palk
Observations: 27,516
Fixed-effects: id: 4,586,  aasta: 6
Standard-errors: Clustered (id) 
           Estimate Std. Error t value Pr(&gt;|t|)    
koolitatud 0.208758   0.093343 2.23645  0.02537 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 2.61339     Adj. R2: 0.727401
                Within R2: 4.309e-4</code></pre>
</div>
</div>
<p>Näeme, et koolituse mõju ajas kasvab oluliselt.</p>
<p>Võime võrrelda ka hinnatuid mudelid</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(m_twfe, m_twfedyn)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          m_twfe          m_twfedyn
Dependent Var.:             palk               palk
                                                   
koolitatud      0.2088* (0.0933)                   
aeg_m3                             -0.0552 (0.1539)
aeg_m2                              0.0735 (0.0743)
aeg_0                             -0.1304. (0.0726)
aeg_1                            0.3485*** (0.1035)
aeg_2                            0.5314*** (0.1253)
aeg_3                            0.7095*** (0.1763)
Fixed-Effects:  ---------------- ------------------
id                           Yes                Yes
aasta                        Yes                Yes
_______________ ________________ __________________
S.E.: Clustered           by: id             by: id
Observations              27,516             27,516
R2                       0.77289            0.77348
Within R2                0.00043            0.00303
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Dünaamiline mudel ei sunni koolituse mõju olema igal koolitusjärgsel aastal sama. Iga sündmusaja koefitsient näitab erinevust võrreldes võrdlusperioodiga -1, st viimase koolituseelse aastaga. Koolituseelsed koefitsiendid (-3, -2) on kasulikud paralleelsete trendide eeldust toetava diagnostikana: ideaalis ei tohiks enne koolitust olla selget süstemaatilist erinevust.</p>
<p>Pangem tähele, et kui koolitus algab erinevatele inimestele erinevatel hetkedel (nn staggered treatment) siis on TWFE sündmusuuring olulise piiranguga. Kui erinevad rühmad saavad meedet eri ajal, võivad mõnes võrdluses kontrollina toimida inimesed, kes on juba varem meedet saanud. Kui meetme mõju muutub ajas või erineb kohortide vahel, võib see dünaamilisi koefitsiente moonutada. Seetõttu kasutatakse keerulisemaid meetodeid.</p>
</section>
<section id="keerulisemad-ja-paindlikumad-mudelid---vabatahtlik" class="level3">
<h3 class="anchored" data-anchor-id="keerulisemad-ja-paindlikumad-mudelid---vabatahtlik">Keerulisemad ja paindlikumad mudelid - vabatahtlik</h3>
<section id="sunabrahami-dünaamiline-hinnang" class="level4">
<h4 class="anchored" data-anchor-id="sunabrahami-dünaamiline-hinnang">Sun–Abrahami dünaamiline hinnang</h4>
<p>Sun–Abrahami meetod on mõeldud just staggered treatment’i olukorraks. See arvestab eraldi kohorte ning väldib tavapärase TWFE event-study problemaatilisi juba-meetmes osalenud versus hiljem-osalenud võrdlusi.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>m_dynamic <span class="ot">&lt;-</span> <span class="fu">feols</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  palk <span class="sc">~</span> <span class="fu">sunab</span>(</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    koolitusaasta,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    aasta,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">ref.p =</span> <span class="sc">-</span><span class="dv">1</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|</span> id <span class="sc">+</span> aasta,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dfl,</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster =</span> <span class="sc">~</span> id</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_dynamic)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: palk
Observations: 27,516
Fixed-effects: id: 4,586,  aasta: 6
Standard-errors: Clustered (id) 
           Estimate Std. Error   t value   Pr(&gt;|t|)    
aasta::-3 -0.011354   0.153666 -0.073886 9.4110e-01    
aasta::-2  0.107777   0.076435  1.410054 1.5859e-01    
aasta::0  -0.079586   0.074352 -1.070386 2.8450e-01    
aasta::1   0.462711   0.105312  4.393739 1.1393e-05 ***
aasta::2   0.566100   0.127318  4.446348 8.9407e-06 ***
aasta::3   0.680453   0.182050  3.737731 1.8795e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 2.60894     Adj. R2: 0.728223
                Within R2: 0.003838</code></pre>
</div>
</div>
<p><code>sunab(koolitusaasta, aasta)</code> loob sisuliselt kohordi × sündmusaja mõjud. Kõigepealt võrreldakse näiteks 2010. aastal koolitatud inimesi sobiva kontrollrühmaga nende sündmusaja lõikes ning eraldi tehakse sama 2011. aastal koolitatutega. Seejärel agregeeritakse need kohordispetsiifilised mõjud sündmusaja järgi.</p>
<p>Oluline erinevus tavapärasest TWFE event-study’st on see, et hinnang ei pea kasutama juba meetmes osalenud kohorti teise meetme kohordi kontrollina. <code>ref.p = -1</code> tähendab, et võrdlusperioodiks on viimane aasta enne koolitust. Seega saab koefitsiente tõlgendada kui mõju võrreldes viimase koolituseelse aastaga.</p>
<p>Ka Sun–Abrahami mudelis on koolituseelsed koefitsiendid statistiliselt ebaolulised. Koolituse aasta mõju on samuti ebaoluline. Esimesel, teisel ja kolmandal koolitusjärgsel aastal on mõju vastavalt umbes <strong>0,463</strong>, <strong>0,566</strong> ja <strong>0,680 tuhat eurot</strong>, kõik statistiliselt olulised. Seega toetab see mudel järeldust, et koolituse mõju palgale ei teki kohe, vaid ilmneb eelkõige alates esimesest koolitusjärgsest aastast.</p>
<p>Mudelite võrdlus</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(m_twfe, m_twfedyn, m_dynamic)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          m_twfe          m_twfedyn          m_dynamic
Dependent Var.:             palk               palk               palk
                                                                      
koolitatud      0.2088* (0.0933)                                      
aeg_m3                             -0.0552 (0.1539)                   
aeg_m2                              0.0735 (0.0743)                   
aeg_0                             -0.1304. (0.0726)                   
aeg_1                            0.3485*** (0.1035)                   
aeg_2                            0.5314*** (0.1253)                   
aeg_3                            0.7095*** (0.1763)                   
aasta = -3                                            -0.0114 (0.1537)
aasta = -2                                             0.1078 (0.0764)
aasta = 0                                             -0.0796 (0.0743)
aasta = 1                                           0.4627*** (0.1053)
aasta = 2                                           0.5661*** (0.1273)
aasta = 3                                           0.6805*** (0.1820)
Fixed-Effects:  ---------------- ------------------ ------------------
id                           Yes                Yes                Yes
aasta                        Yes                Yes                Yes
_______________ ________________ __________________ __________________
S.E.: Clustered           by: id             by: id             by: id
Observations              27,516             27,516             27,516
R2                       0.77289            0.77348            0.77366
Within R2                0.00043            0.00303            0.00384
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Esitame viimase mudeli kordajad ka joonisel</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">iplot</span>(</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  m_dynamic,</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">ref.line =</span> <span class="dv">0</span>,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Aastad koolitusest"</span>,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Mõju palgale"</span>,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Koolituse mõju palgale"</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-difdif_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>iplot()</code> on <code>fixest</code> paketis mugav viis event-study koefitsientide ja usaldusvahemike joonistamiseks. Graafikult on dünaamikat tavaliselt lihtsam lugeda kui regressioonitabelist: enne meedet peaksid hinnangud olema nulli lähedal ning pärast meedet näeme, millal mõju tekib ja kuidas see ajas muutub.</p>
</section>
<section id="sunabrahami-keskmine-att" class="level4">
<h4 class="anchored" data-anchor-id="sunabrahami-keskmine-att">Sun–Abrahami keskmine ATT</h4>
<p>Sun–Abrahami meetodil saame leida ka keskmise mõju.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>m_att <span class="ot">&lt;-</span> <span class="fu">feols</span>(</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  palk <span class="sc">~</span> <span class="fu">sunab</span>(</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    koolitusaasta,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    aasta,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">att =</span> <span class="cn">TRUE</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|</span> id <span class="sc">+</span> aasta,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dfl,</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster =</span> <span class="sc">~</span> id</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_att)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: palk
Observations: 27,516
Fixed-effects: id: 4,586,  aasta: 6
Standard-errors: Clustered (id) 
                        Estimate Std. Error   t value   Pr(&gt;|t|)    
aasta::-3:cohort::2011 -0.011354   0.153666 -0.073886 0.94110405    
aasta::-2:cohort::2010  0.127494   0.114251  1.115915 0.26451706    
aasta::-2:cohort::2011  0.086467   0.103093  0.838728 0.40166576    
ATT                     0.370136   0.097702  3.788411 0.00015356 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 2.60894     Adj. R2: 0.728223
                Within R2: 0.003838</code></pre>
</div>
</div>
<p>Dünaamilised koefitsiendid vastavad küsimusele „kuidas mõju muutub ajas pärast koolitust?“. Sageli tahame lisaks ühte kokkuvõtvat arvu: kui suur on keskmine mõju kõigi meetmes osalenud inimeste ja kõigi koolitusjärgsete perioodide peale kokku. <code>att = TRUE</code> palub Sun–Abrahami kohordispetsiifilised mõjud selliseks keskmiseks ATT-ks agregeerida.</p>
<p>Seda arvu on lihtsam näiteks poliitikakokkuvõttes esitada, kuid see peidab dünaamika. Seetõttu on hea tava näidata kõrvuti nii keskmist ATT-d kui ka sündmuspõhist joonist.</p>
<p>Keskmine Sun–Abrahami ATT on umbes <strong>0,370 tuhat eurot</strong> ehk <strong>370 eurot aastas</strong> ning on statistiliselt oluline. See on suurem kui lihtsa konstantse mõjuga TWFE hinnang 0.208. Erinevus näitab, et staggered treatment’i ja ajas muutuva mõju korral võib üks tavapärane TWFE koefitsient anda teistsuguse kokkuvõtte kui kohordipõhiste mõjude korrektne agregeerimine.</p>
</section>
<section id="callawaysantanna-meetod" class="level4">
<h4 class="anchored" data-anchor-id="callawaysantanna-meetod">Callaway–Sant’Anna meetod</h4>
<p>Callaway–Sant’Anna lähenemine alustab kõige detailsemast objektist: <strong>ATT(g,t)</strong> ehk mõju konkreetsele meetmes osalenud kohordile <code>g</code> konkreetsel kalendriaastal <code>t</code>. Seejärel saab neid hinnanguid agregeerida mitmel eri viisil.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>att_gr <span class="ot">&lt;-</span> <span class="fu">att_gt</span>(</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">yname =</span> <span class="st">"palk"</span>,</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">tname =</span> <span class="st">"aasta"</span>,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">idname =</span> <span class="st">"id"</span>,</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">gname =</span> <span class="st">"koolitusaasta"</span>,</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xformla =</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dfl,</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">panel =</span> <span class="cn">TRUE</span>,</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">control_group =</span> <span class="st">"nevertreated"</span>,</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">est_method =</span> <span class="st">"dr"</span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(att_gr)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
att_gt(yname = "palk", tname = "aasta", idname = "id", gname = "koolitusaasta", 
    xformla = ~1, data = dfl, panel = TRUE, control_group = "nevertreated", 
    est_method = "dr")

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. &lt;https://doi.org/10.1016/j.jeconom.2020.12.001&gt;, &lt;https://arxiv.org/abs/1803.09015&gt; 

Group-Time Average Treatment Effects:
 Group Time ATT(g,t) Std. Error [95% Simult.  Conf. Band]  
  2010 2009  -0.1275     0.1147       -0.4445      0.1895  
  2010 2010  -0.3035     0.1089       -0.6045     -0.0025 *
  2010 2011   0.5115     0.1391        0.1272      0.8958 *
  2010 2012   0.7603     0.1629        0.3101      1.2106 *
  2010 2013   0.6805     0.1881        0.1606      1.2004 *
  2011 2009   0.0978     0.1193       -0.2318      0.4274  
  2011 2010  -0.0865     0.1082       -0.3854      0.2125  
  2011 2011   0.1624     0.1033       -0.1231      0.4480  
  2011 2012   0.4100     0.1466        0.0049      0.8150 *
  2011 2013   0.3562     0.1850       -0.1552      0.8676  
---
Signif. codes: `*' confidence band does not cover 0

P-value for pre-test of parallel trends assumption:  0.32533
Control Group:  Never Treated,  Anticipation Periods:  0
Estimation Method:  Doubly Robust</code></pre>
</div>
</div>
<p><code>att_gt()</code> hindab mõju eraldi iga meetme osaleva kohordi ja kalendriaasta kombinatsiooni jaoks. Näiteks saab 2010. aastal koolitatud rühmal olla 2011. aastal üks mõju ja 2012. aastal teine mõju. Kontrollrühmaks määrame siin selgelt <code>nevertreated</code>, st inimesed, kes ei saanud koolitust ühelgi vaatlusperioodil.</p>
<p>Selline ülesehitus väldib vajadust suruda kogu informatsioon kohe ühte TWFE koefitsienti. Meetod teeb esmalt sobivad 2×2 DiD võrdlused ja alles seejärel agregeerib need vastavalt uurimisküsimusele. <code>est_method = "dr"</code> kasutab doubly robust DiD hinnangut; kuna <code>xformla = ~ 1</code>, ei lisa me selles etapis uusi selgitavaid tegureid.</p>
<ol start="2010" type="1">
<li>aasta kohordi puhul on mõju alates 2011. aastast selgelt positiivne: hinnangud on ligikaudu <strong>0,5115</strong>, <strong>0,7603</strong> ja <strong>0,6805 tuhat eurot</strong> aastatel 2011–2013. 2011. aasta kohordi hinnangud on väiksemad ja simuleeritud usaldusvahemiku järgi statistiliselt ebaolulised. Paralleelsete trendide ühise pre-testi p-väärtus on umbes <strong>0,33</strong>, mistõttu andmed ei anna põhjust paralleelsete trendide eeldust enne meedet tagasi lükata.</li>
</ol>
<p><strong>Keskmine efekt</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>overall_att <span class="ot">&lt;-</span> <span class="fu">aggte</span>(att_gr, <span class="at">type =</span> <span class="st">"simple"</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(overall_att)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
aggte(MP = att_gr, type = "simple")

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. &lt;https://doi.org/10.1016/j.jeconom.2020.12.001&gt;, &lt;https://arxiv.org/abs/1803.09015&gt; 

    ATT    Std. Error     [ 95%  Conf. Int.]  
 0.3701        0.0947     0.1846      0.5557 *


---
Signif. codes: `*' confidence band does not cover 0

Control Group:  Never Treated,  Anticipation Periods:  0
Estimation Method:  Doubly Robust</code></pre>
</div>
</div>
<p><code>aggte()</code> võtab <code>att_gt()</code> loodud rühma- ja ajaspetsiifilised mõjud ning teeb neist uurimisküsimusele sobiva kokkuvõtte. <code>type = "simple"</code> annab ühe üldise ATT: kui suur on keskmine mõju meetme osalenud inimestele kõigi meetmejärgsete kohordi-aasta kombinatsioonide peale kokku.</p>
<p>See on kõige lähem vaste küsimusele „mis oli koolituse keskmine mõju?“. Samas ei näita see, millal mõju tekkis ega kas mõju oli eri kohortides erinev.</p>
<p>Callaway–Sant’Anna üldine ATT on <strong>0,370 tuhat eurot</strong>. See on sisuliselt sama kui Sun–Abrahami agregeeritud ATT, mis on hea sisuline kontroll: kaks staggered treatment’i jaoks sobivat meetodit annavad siin keskmise mõju kohta väga sarnase tulemuse.</p>
<p><strong>Dünaamiline mõju sündmusaja järgi</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>dyn_att <span class="ot">&lt;-</span> <span class="fu">aggte</span>(att_gr, <span class="at">type =</span> <span class="st">"dynamic"</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dyn_att)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
aggte(MP = att_gr, type = "dynamic")

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. &lt;https://doi.org/10.1016/j.jeconom.2020.12.001&gt;, &lt;https://arxiv.org/abs/1803.09015&gt; 


Overall summary of ATT's based on event-study/dynamic aggregation:  
    ATT    Std. Error     [ 95%  Conf. Int.]  
 0.4074        0.1034     0.2048      0.6101 *


Dynamic Effects:
 Event time Estimate Std. Error [95% Simult.  Conf. Band]  
         -2   0.0978     0.1223       -0.2110      0.4066  
         -1  -0.1078     0.0782       -0.3054      0.0898  
          0  -0.0796     0.0677       -0.2505      0.0913  
          1   0.4627     0.1076        0.1910      0.7344 *
          2   0.5661     0.1284        0.2419      0.8903 *
          3   0.6805     0.1802        0.2254      1.1355 *
---
Signif. codes: `*' confidence band does not cover 0

Control Group:  Never Treated,  Anticipation Periods:  0
Estimation Method:  Doubly Robust</code></pre>
</div>
</div>
<p><code>type = "dynamic"</code> rühmitab ATT(g,t) hinnangud selle järgi, mitu aastat on koolitusest möödunud. Seega ühendatakse näiteks kõik kohordid nende esimesel koolitusjärgsel aastal üheks sündmusaja <code>+1</code> hinnanguks. See on Callaway–Sant’Anna event-study versioon.</p>
<p>Dünaamiline agregeerimine on eriti kasulik kahe küsimuse jaoks: kas enne meedet oli näha erinevaid trende ning kui kiiresti meetme mõju pärast meetme algust tekib. Nagu Sun–Abrahami puhul, on oluline vaadata nii koolituseelseid kui ka -järgseid koefitsiente.</p>
<p>Sündmusajal <code>0</code> on mõju umbes <strong>-0,0796 tuhat eurot</strong> ja statistiliselt ebaoluline. Esimesel, teisel ja kolmandal koolitusjärgsel aastal on mõjud ligikaudu <strong>0,463</strong>, <strong>0,566</strong> ja <strong>0,681 tuhat eurot</strong> ning kõik on statistiliselt olulised. Dünaamiline muster on praktiliselt sama Sun–Abrahami mudeliga: mõju tekib viitajaga ja püsib järgmiste aastate jooksul positiivne.</p>
</section>
</section>
</section>
<section id="mõju-kalendriaja-järgi" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="mõju-kalendriaja-järgi"><span class="header-section-number">6.4</span> Mõju kalendriaja järgi</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>cal_att <span class="ot">&lt;-</span> <span class="fu">aggte</span>(att_gr, <span class="at">type =</span> <span class="st">"calendar"</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cal_att)</span></code></pre></div><button title="Kopeeri lõikelauale" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
aggte(MP = att_gr, type = "calendar")

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. &lt;https://doi.org/10.1016/j.jeconom.2020.12.001&gt;, &lt;https://arxiv.org/abs/1803.09015&gt; 


Overall summary of ATT's based on calendar time aggregation:  
    ATT    Std. Error     [ 95%  Conf. Int.]  
 0.2892        0.0911     0.1106      0.4678 *


Time Effects:
 Time Estimate Std. Error [95% Simult.  Conf. Band]  
 2010  -0.3035     0.1080       -0.5517     -0.0553 *
 2011   0.3438     0.0963        0.1223      0.5652 *
 2012   0.5919     0.1182        0.3201      0.8638 *
 2013   0.5246     0.1365        0.2108      0.8384 *
---
Signif. codes: `*' confidence band does not cover 0

Control Group:  Never Treated,  Anticipation Periods:  0
Estimation Method:  Doubly Robust</code></pre>
</div>
</div>
<p><code>type = "calendar"</code> vastab teistsugusele küsimusele kui event-study: selle asemel, et küsida „mitu aastat pärast meedet“, küsime „kui suur oli meetme mõju konkreetsel kalendriaastal?“. Kõik selleks aastaks juba meetmes osalenud kohordid agregeeritakse vastava aasta hinnangusse.</p>
<p>Kalendriaja agregeerimine võib olla kasulik siis, kui majanduskeskkond või programmi rakendamine muutub aastati. Näiteks võib sama koolitusprogramm anda majanduslanguse ajal teistsuguse tulemuse kui kiire palgakasvu perioodil.</p>
<p>Kalendriaja järgi agregeeritud keskmine ATT on umbes <strong>0,289 tuhat eurot</strong>. 2010. aasta hinnang on negatiivne, kuid ebaoluline; 2011., 2012. ja 2013. aasta mõjud on vastavalt umbes <strong>0.344</strong>, <strong>0,592</strong> ja <strong>0,523 tuhat eurot</strong> ning statistiliselt olulised. See kinnitab üldpilti, et positiivne mõju on nähtav peamiselt pärast esimest koolitusaastat.</p>
<section id="kokkuvõte" class="level4">
<h4 class="anchored" data-anchor-id="kokkuvõte">Kokkuvõte</h4>
<p>Selles näites annavad staggered treatment’i jaoks sobivad Sun–Abrahami ja Callaway–Sant’Anna meetodid väga sarnase tulemuse. Sündmusuuring näitab, et mõju ei teki kohe koolituse aastal. Positiivne mõju ilmneb peamiselt alates esimesest koolitusjärgsest aastast ning jääb järgmisteks aastateks suurusjärku 0,6–0,7 tuhat eurot aastas.</p>
<p>Selle näite peamine õppetund on, et staggered treatment’i korral ei piisa alati tavapärasest TWFE mudelist. Kui mõju võib ajas muutuda, on mõistlik hinnata kohordi- ja ajaspetsiifilisi mõjusid ning kasutada nende korrektseks agregeerimiseks Sun–Abrahami või Callaway–Sant’Anna meetodit.</p>
</section>
<section id="viited" class="level3">
<h3 class="anchored" data-anchor-id="viited">Viited:</h3>
<p>Callaway, Brantly and Pedro H.C. Sant’Anna. “Difference-in-Differences with Multiple Time Periods.” Journal of Econometrics, Vol. 225, No.&nbsp;2, pp.&nbsp;200-230, 2021. <a href="https://doi.org/10.1016/j.jeconom.2020.12.001" class="uri">https://doi.org/10.1016/j.jeconom.2020.12.001</a>, <a href="https://arxiv.org/abs/1803.09015" class="uri">https://arxiv.org/abs/1803.09015</a></p>
<p>Liyang Sun, Sarah Abraham, “Estimating dynamic treatment effects in event studies with heterogeneous treatment effects”, Journal of Econometrics, Volume 225, Issue 2, 2021, Pages 175-199, https://doi.org/10.1016/j.jeconom.2020.09.006. (https://www.sciencedirect.com/science/article/pii/S030440762030378X)</p>
<p>Lisada</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopeeritud!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopeeritud!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-regressioon.html" class="pagination-link" aria-label="Regressioonimudeli kasutamine">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regressioonimudeli kasutamine</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-rdd.html" class="pagination-link" aria-label="Regressiooni katkemise meetod">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regressiooni katkemise meetod</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>